-- Per-day quiz bank expansion for cohort 56268633-9e93-4305-af6a-1b622a833d8e
-- Generated: 2026-04-21. Replaces prior 3-question banks with 5-7 grounded questions per day.
-- After applying this seed, run quizzes_enhancements_20260423.sql to append transfer + spaced-recall items (2 per day). That file is idempotent (safe to re-run).

begin;

-- ============================================================================
-- DAY 1 — What AI is (and isn't) + real-world AI
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Day 1 separates 'chatbot' from 'LLM'. Which statement matches that distinction?","type":"single","options":[{"text":"A chatbot is the app wrapper around an LLM; the LLM is the underlying pattern-matching model.","correct":true},{"text":"Chatbots and LLMs are interchangeable terms.","correct":false},{"text":"A chatbot is trained from scratch each conversation; the LLM is the memory layer.","correct":false},{"text":"An LLM is the UI and the chatbot is the math.","correct":false}],"explanation":"ChatGPT/Claude/Gemini are apps wrapped around a large language model. The same model can power many chatbots; the wrapper adds memory, UI, and guardrails."},
  {"q":"Select ALL statements that belong in the 'What AI is' column from Day 1.","type":"multi","options":[{"text":"A pattern machine trained on trillions of sentences.","correct":true},{"text":"Stateless by default unless an app adds memory.","correct":true},{"text":"Conscious, with desires and feelings.","correct":false},{"text":"Already shipping in Maps, Gmail spam, UPI fraud detection.","correct":true},{"text":"A search engine that finds documents that already exist.","correct":false}],"explanation":"Day 1 framed AI as a stateless pattern machine that's been embedded in everyday Indian tech for a decade. Consciousness and 'search' are explicit 'AI isn't' items."},
  {"q":"In the Day 1 lab you ran the same placement-mentor prompt across three tools. What was the core learning goal?","type":"single","options":[{"text":"Prove ChatGPT is always best.","correct":false},{"text":"Feel the personality differences between ChatGPT, Claude, and Gemini on identical input.","correct":true},{"text":"Measure token counts across models.","correct":false},{"text":"Verify each tool's citations.","correct":false}],"explanation":"The 'same prompt, three brains' lab makes you feel tone, specificity, and length differences — the setup for Day 2's tokens/weights explanation."},
  {"q":"Day 1 says AI is 'confidently wrong 15-30% of the time depending on task.' What is the term for this?","type":"single","options":[{"text":"Tokenization","correct":false},{"text":"Temperature","correct":false},{"text":"Hallucination","correct":true},{"text":"Fine-tuning","correct":false}],"explanation":"Hallucination = AI asserting false things with total confidence. Day 4 goes deeper; today you just learn to expect and verify."},
  {"q":"Which is the single 150-word Day-0 baseline artefact you submit on Day 1?","type":"single","options":[{"text":"A tokenizer notebook.","correct":false},{"text":"An honest reflection titled 'What surprised me about AI today' with NO AI assistance.","correct":true},{"text":"A capstone one-pager.","correct":false},{"text":"A Claude Project with your resume uploaded.","correct":false}],"explanation":"The Day-0 baseline is deliberately AI-free so Day 30's transformation is measurable, not remembered."},
  {"q":"In one sentence: why does Day 1 insist AI is 'not a search engine'?","type":"text","options":[],"explanation":"Strong answer: search retrieves documents that already exist; generative AI produces plausible-sounding output that may not. The distinction matters most for citations and facts that require verification."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 1;

-- ============================================================================
-- DAY 2 — Inside an LLM: tokens, weights, attention
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Roughly how many tokens is one English word on average, per Day 2?","type":"single","options":[{"text":"1 token = 1 character","correct":false},{"text":"About 3/4 of a word = 1 token (roughly 3-4 characters)","correct":true},{"text":"1 token = 1 sentence","correct":false},{"text":"1 token = 1 paragraph","correct":false}],"explanation":"A token is ~3-4 characters or ~3/4 of an English word. That's why 'Bengaluru' is 3 tokens and 'hello' is 1."},
  {"q":"Day 2's one-line summary of how an LLM produces text is:","type":"single","options":[{"text":"retrieve → rank → return","correct":false},{"text":"tokenise → weigh → attend → predict → repeat","correct":true},{"text":"prompt → compile → execute","correct":false},{"text":"encode → decode → display","correct":false}],"explanation":"That five-verb loop is Day 2's mental model for every response the model generates, one token at a time."},
  {"q":"Select ALL reasons the SAME prompt gives different answers on ChatGPT vs Claude vs Gemini.","type":"multi","options":[{"text":"Different training data mixes.","correct":true},{"text":"Different RLHF and system prompts.","correct":true},{"text":"Temperature and sampling settings.","correct":true},{"text":"The three apps all have the same weights.","correct":false},{"text":"Hardware choice (GPU vs TPU) changes the output deterministically.","correct":false}],"explanation":"Different weights + different training choices + different temperature/system-prompt defaults = three personalities from identical input."},
  {"q":"If model weights are FROZEN after training, how does ChatGPT 'remember' what you said last week?","type":"single","options":[{"text":"The weights update live as you chat.","correct":false},{"text":"An app-level memory layer shovels prior context back into the prompt; the weights don't change.","correct":true},{"text":"It re-downloads a new model per session.","correct":false},{"text":"Browser cookies store the model's updates.","correct":false}],"explanation":"Memory is an app feature (ChatGPT Memory, Claude Projects) that injects prior facts into each new prompt. The underlying weights are immutable post-training."},
  {"q":"Why does 'Bengaluru' tokenize into 3 tokens while 'hello' tokenizes into 1?","type":"single","options":[{"text":"Hindi words are always 3 tokens.","correct":false},{"text":"Common English words get dedicated single tokens; less-frequent words get split into sub-word pieces.","correct":true},{"text":"Non-English words aren't tokenizable.","correct":false},{"text":"Longer words always get more tokens — one per syllable.","correct":false}],"explanation":"Tokenizers are trained by frequency. Rare or non-English tokens split into sub-words, which is also why non-English text is more expensive per character."},
  {"q":"The 'attention' mechanism inside transformers does what, in plain English?","type":"single","options":[{"text":"Decides which earlier tokens matter most when predicting the next token.","correct":true},{"text":"Prevents the model from falling asleep between requests.","correct":false},{"text":"Picks which GPU handles each request.","correct":false},{"text":"Masks profanity from the training data.","correct":false}],"explanation":"Attention computes a weighted score across prior tokens so the model 'looks back' at the parts of your prompt that matter for the next word."},
  {"q":"In one sentence, explain tokens to a parent with zero jargon.","type":"text","options":[],"explanation":"Strong answer uses an everyday analogy (per-SMS pricing, sliced bread, puzzle pieces) and names one practical consequence (longer inputs cost more / run slower)."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 2;

-- ============================================================================
-- DAY 3 — The AI tool landscape: 7 classes, open vs closed, Indian stack
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Day 3 teaches 7 tool classes. Which is NOT one of them?","type":"single","options":[{"text":"Everyday chat","correct":false},{"text":"Research / knowledge work","correct":false},{"text":"Block-chain ledgers","correct":true},{"text":"Creative (image/video/voice)","correct":false},{"text":"Automation","correct":false}],"explanation":"The 7 classes are chat, open-source/local, Indian AI, research, creative, code/vibe-coding, and automation."},
  {"q":"The difference between OPEN weights and CLOSED weights, per Day 3:","type":"single","options":[{"text":"Open = free to use; closed = paid.","correct":false},{"text":"Open = the model file is downloadable for you to inspect/modify/run; closed = the model sits behind a company's API.","correct":true},{"text":"Open = trained on open data; closed = trained on private data.","correct":false},{"text":"Open = runs in the browser; closed = runs on the cloud.","correct":false}],"explanation":"Openness is about weight availability. Llama/Qwen/DeepSeek are open-weight; GPT-4o/Claude/Gemini are closed."},
  {"q":"Select ALL models that are part of the Indian AI stack highlighted in Day 3.","type":"multi","options":[{"text":"Sarvam AI","correct":true},{"text":"BharatGPT (CoRover)","correct":true},{"text":"Krutrim (Ola)","correct":true},{"text":"Mistral","correct":false},{"text":"DeepSeek","correct":false}],"explanation":"Sarvam, BharatGPT, and Krutrim are the three Indian names Day 3 insists you remember as a hiring/ecosystem edge."},
  {"q":"Day 3's three 'which tool for which job' heuristics include asking:","type":"multi","options":[{"text":"'Is it a conversation or a search?'","correct":true},{"text":"'Is the input my own private data?'","correct":true},{"text":"'Am I writing or coding?'","correct":true},{"text":"'Is the model Chinese?'","correct":false}],"explanation":"These three filters route ~90% of tool decisions. Conversations → chat; searches → Perplexity/NotebookLM; writing → Claude; coding → Cursor/Claude Code."},
  {"q":"If open models are 'almost as good and free,' why does OpenAI still make billions?","type":"single","options":[{"text":"Raw model quality is their only moat.","correct":false},{"text":"Distribution, integration, reliability and SLAs matter — 'free to download' ≠ 'free to serve.'","correct":true},{"text":"They own the only GPUs in the world.","correct":false},{"text":"Open models don't actually work.","correct":false}],"explanation":"Day 3 argues the moat is distribution (ChatGPT app), enterprise integration, and the non-trivial cost of actually self-hosting a 400B model."},
  {"q":"Name one task from your life where NotebookLM would beat Perplexity, and why (one sentence).","type":"text","options":[],"explanation":"Strong answer mentions a task where the source set is YOUR private docs (syllabus PDFs, lecture notes, your own research) — NotebookLM refuses to answer from the open web, which is a feature for groundedness."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 3;

-- ============================================================================
-- DAY 4 — CREATE prompt framework
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"What does the 'E' in CREATE stand for — in BOTH positions?","type":"single","options":[{"text":"Examples and Evaluation","correct":true},{"text":"Empathy and Enthusiasm","correct":false},{"text":"Engagement and Ethics","correct":false},{"text":"Encoding and Embedding","correct":false}],"explanation":"CREATE = Context, Role, Examples, Active constraints, Tone, Evaluation. Both E's are load-bearing: Examples teach format; Evaluation tells the model how you'll judge."},
  {"q":"Which prompt pattern adds 'Think step by step before answering' and dramatically helps on reasoning tasks?","type":"single","options":[{"text":"Zero-shot","correct":false},{"text":"Few-shot","correct":false},{"text":"Chain-of-thought (CoT)","correct":true},{"text":"Structured output","correct":false}],"explanation":"CoT forces the model to surface reasoning before the final answer and works shockingly well on math, logic, and debugging."},
  {"q":"Why does asking for JSON output matter — pick ALL that apply.","type":"multi","options":[{"text":"It bridges AI text into software (spreadsheets, APIs, pipelines).","correct":true},{"text":"It is a cheat code that the makers are trying to patch.","correct":false},{"text":"It forces the model to be machine-parseable so humans don't have to re-type.","correct":true},{"text":"It guarantees the model will be more accurate on every task.","correct":false}],"explanation":"Structured output is the leap from 'AI gives me text' to 'AI gives me data.' It's how adults use LLMs, not a trick."},
  {"q":"Day 4 distinguishes PROMPT engineering from CONTEXT engineering. Which is true?","type":"single","options":[{"text":"Context engineering is just a fancier prompt.","correct":false},{"text":"Context engineering designs the whole information environment (files, memory, role) that travels with every chat — prompts are one-off messages.","correct":true},{"text":"Context engineering is illegal in most countries.","correct":false},{"text":"They are the same thing with different brands.","correct":false}],"explanation":"The two are complementary but distinct — prompt engineering = one message; context engineering = the persistent brief (Day 19 builds CLAUDE.md for this)."},
  {"q":"In the Day 4 lab you iterate one prompt five times. What is V1?","type":"single","options":[{"text":"A fully CREATE-structured prompt with examples and JSON.","correct":false},{"text":"Whatever lazy 10-second version you'd normally type.","correct":true},{"text":"The instructor's example prompt.","correct":false},{"text":"A prompt written by Claude for you.","correct":false}],"explanation":"V1 is your honest lazy baseline so V5 feels like a transformation. Then you add C+R, then E, then A+T, then structured output."},
  {"q":"Name one CREATE letter you skip most often — and the concrete failure mode it causes (1 sentence).","type":"text","options":[],"explanation":"Strong answer picks one specific letter (not 'all of them') and names a specific failure — e.g., 'I skip Examples, so the model defaults to LinkedIn-bro tone every time.'"}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 4;

-- ============================================================================
-- DAY 5 — Week-1 show-and-tell + Personal AI Stack v1
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Which four sections does Day 5's Personal AI Stack v1 contain?","type":"single","options":[{"text":"My AI Tools, My Top 10 Prompts, My Top 3 Use Cases, My Next Bet","correct":true},{"text":"Resume, Transcript, Capstone Ideas, References","correct":false},{"text":"Hardware, Software, Network, Budget","correct":false},{"text":"Goals, Risks, Metrics, Timeline","correct":false}],"explanation":"The four sections form a 1-page artefact you revise every Sunday. 'Next Bet' is the single AI skill you want to own by Day 30."},
  {"q":"The Day 5 show-and-tell uses a hard time cap. How long is each student's pitch?","type":"single","options":[{"text":"30 seconds","correct":false},{"text":"2 minutes","correct":true},{"text":"5 minutes","correct":false},{"text":"10 minutes","correct":false}],"explanation":"Each student delivers a 2-minute pitch on their best AI moment from Days 1-4; the constraint IS the point."},
  {"q":"Select ALL myths Day 5 explicitly debunks.","type":"multi","options":[{"text":"'One prompt rules them all.'","correct":true},{"text":"'AI replaces thinking.'","correct":true},{"text":"'AI gives you leverage — but only if you had direction.'","correct":false},{"text":"'Just ask it anything — context is optional.'","correct":true}],"explanation":"Day 5 lists these as LinkedIn myths. The direction/leverage line is the TRUTH, not the myth."},
  {"q":"In Priya's worked example, her Week-1 wins were...","type":"single","options":[{"text":"Debugging Python and writing unit tests.","correct":false},{"text":"Turning grandmother's handwritten recipes into a blog + translating with Sarvam + designing captions.","correct":true},{"text":"Fine-tuning Llama-3 on IIT lecture notes.","correct":false},{"text":"Building a RAG system for a law firm.","correct":false}],"explanation":"Priya (Civil, 7.2 CGPA) is Day 5's reminder that a good stack fits YOUR life, not a CS major's."},
  {"q":"What are the 'two unspoken rules of the cohort' per Day 5?","type":"single","options":[{"text":"Steal shamelessly (with credit) + Share your failures.","correct":true},{"text":"Grind hard + Never sleep.","correct":false},{"text":"Only use paid tools + Avoid open source.","correct":false},{"text":"Turn in assignments late + Blame the instructor.","correct":false}],"explanation":"Steal-with-credit keeps the cohort compounding; sharing fails teaches more than ten wins."},
  {"q":"In one sentence: which Day-0 belief about AI are you leaving Day 5 without?","type":"text","options":[],"explanation":"Strong answer names a specific belief you held on Day 1 (e.g., 'Claude and ChatGPT were basically the same') and the concrete moment of evidence that flipped it."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 5;

-- ============================================================================
-- DAY 6 — Five frontier chatbots + Memory + Projects (Jarvis)
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"What is the difference between 'Memory' and 'Projects' in consumer chatbots, per Day 6?","type":"single","options":[{"text":"They're the same feature with different names.","correct":false},{"text":"Memory = the model writes facts about YOU across chats; Projects = a pinned workspace with files + system prompt (e.g., Claude Projects, GPTs, Gems).","correct":true},{"text":"Memory is paid; Projects is free.","correct":false},{"text":"Memory works only in Gemini; Projects only in Claude.","correct":false}],"explanation":"Memory is persistent facts; Projects are pinned workspaces. Both fight the amnesia of a blank chat."},
  {"q":"Which model would Day 6 recommend for summarising a 90-page Google Doc your professor shared on Drive?","type":"single","options":[{"text":"Grok","correct":false},{"text":"Kimi","correct":false},{"text":"Gemini","correct":true},{"text":"Claude Haiku 1","correct":false}],"explanation":"Day 6's field guide: Gemini wins on Google Workspace integration and 1M-token PDFs."},
  {"q":"Why does the Day 6 lab build your Jarvis in Claude Projects specifically?","type":"multi","options":[{"text":"Cleanest Projects UI.","correct":true},{"text":"Biggest free-tier file upload budget.","correct":true},{"text":"Best long-form writing.","correct":true},{"text":"Only Claude has memory.","correct":false}],"explanation":"Those three reasons (UI, upload budget, writing) are why Jarvis lives in Claude Projects for the rest of the cohort."},
  {"q":"In the 3-model comparison exercise, WHY does the Claude-with-context answer beat the blank ChatGPT answer?","type":"single","options":[{"text":"Claude is objectively smarter.","correct":false},{"text":"Project knowledge (resume + transcript + 5 capstone ideas) gives Claude the context blank ChatGPT doesn't have.","correct":true},{"text":"ChatGPT was rate-limited.","correct":false},{"text":"Gemini refused to answer.","correct":false}],"explanation":"Same model class, but Claude wins because you pre-loaded context. The lesson: context beats a blank chat every time."},
  {"q":"Day 6's honest field guide pairs each chat model with 'Best at'. Match the best pairing.","type":"single","options":[{"text":"Grok — long-form writing and nuanced reasoning","correct":false},{"text":"Claude — real-time X feed","correct":false},{"text":"Grok — real-time X feed, news, edgy tone","correct":true},{"text":"Kimi — Google Workspace integration","correct":false}],"explanation":"The field guide: Claude=long-form/code review, ChatGPT=code/daily, Gemini=Workspace, Grok=X news, Kimi=Chinese+long docs."},
  {"q":"What's the privacy note Day 6 makes before you start pasting into free-tier chatbots?","type":"text","options":[],"explanation":"Strong answer: anything pasted into free-tier chatbots may be used for training; don't paste Aadhaar, a friend's grades, or company NDAs. Toggle 'improve the model' off or use enterprise tiers for sensitive work."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 6;

-- ============================================================================
-- DAY 7 — Research tools + 4-step hallucination check
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Day 7's 4-step hallucination check is:","type":"single","options":[{"text":"Pray, refresh, restart, scream","correct":false},{"text":"Click the citation, confirm source exists and is reputable, confirm it actually says what the model claims, check the date","correct":true},{"text":"Run it on 3 other models and average","correct":false},{"text":"Ask the model 'are you sure?' three times","correct":false}],"explanation":"Click → confirm source → confirm claim matches → check date. About 10% of the time the citation doesn't support the claim — that's your signal to drop or rewrite."},
  {"q":"Why does NotebookLM refuse to answer from the open web — and when is that a FEATURE?","type":"single","options":[{"text":"It's a bug they haven't fixed.","correct":false},{"text":"Because every answer is grounded in YOUR uploaded sources only — ideal for literature reviews and private corpora.","correct":true},{"text":"Google couldn't afford the search licence.","correct":false},{"text":"It's throttled by the free tier.","correct":false}],"explanation":"Source-grounding is NotebookLM's whole point: you get answers anchored in exactly the PDFs/links you gave it, with clickable source jumps."},
  {"q":"Select ALL research tools Day 7 teaches and when each wins.","type":"multi","options":[{"text":"Perplexity — fast grounded Q&A with inline citations","correct":true},{"text":"NotebookLM — private index over YOUR own sources + Audio Overview podcasts","correct":true},{"text":"Gemini Deep Research — multi-step agent run over 100+ sources, 10-20 page reports","correct":true},{"text":"ChatGPT default — the best grounded-research tool in 2026","correct":false}],"explanation":"Three tools, three jobs. Default ChatGPT isn't grounded — that's why the day exists."},
  {"q":"What is a NotebookLM 'Audio Overview'?","type":"single","options":[{"text":"A voice-to-text transcription of your PDFs.","correct":false},{"text":"An auto-generated podcast with two AI hosts discussing your uploaded sources.","correct":true},{"text":"An AI-generated summary read aloud in your cloned voice.","correct":false},{"text":"A Spotify playlist based on your documents.","correct":false}],"explanation":"Two AI hosts debate/summarise your corpus in ~9 min. Great commute listening and surfaces disagreements across sources."},
  {"q":"The Day 7 lab produces a 1-page brief-<topic>.md. What's the minimum citation requirement?","type":"single","options":[{"text":"At least 1","correct":false},{"text":"At least 3","correct":false},{"text":"At least 5 inline citations","correct":true},{"text":"At least 20","correct":false}],"explanation":"Five+ inline citations, every factual claim linked. Submission also requires one 'I almost quoted this...' moment where you rewrote or dropped a claim after clicking."},
  {"q":"In one sentence: when is it negligent to skip clicking a citation?","type":"text","options":[],"explanation":"Strong answer draws a stakes-based line: casual curiosity = fine; capstone brief / medical / legal / financial claims = click every time. Names the cost of getting it wrong."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 7;

-- ============================================================================
-- DAY 8 — Image + video generation (six-slot template)
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"What are the six slots of Day 8's image-prompt template?","type":"single","options":[{"text":"Subject, Action/state, Setting, Style, Composition, Modifiers","correct":true},{"text":"Who, What, Where, When, Why, How","correct":false},{"text":"Color, Size, Shape, Texture, Light, Mood","correct":false},{"text":"Hook, Setup, Beat, Twist, Payoff, Ask","correct":false}],"explanation":"Specify all six or the model fills gaps you didn't. Generic adjectives → generic images."},
  {"q":"In one sentence, what is a diffusion model actually doing?","type":"single","options":[{"text":"Copy-pasting existing images from the internet.","correct":false},{"text":"Starting from pure noise and denoising step by step, guided by your prompt, until an image emerges.","correct":true},{"text":"Asking Midjourney's servers to render 3D polygons.","correct":false},{"text":"Running a GAN-vs-GAN adversarial match.","correct":false}],"explanation":"Diffusion = sculpting noise into an image. Your prompt is the chisel; more specific nouns = sharper output."},
  {"q":"Which tool would Day 8 trust for a COMMERCIALLY-SAFE LinkedIn banner?","type":"single","options":[{"text":"Midjourney","correct":false},{"text":"Adobe Firefly (trained on licensed data)","correct":true},{"text":"Random SD checkpoint from a Reddit link","correct":false},{"text":"ComfyUI running a leaked model","correct":false}],"explanation":"Firefly is the cohort's fallback for anything you'll publish or submit — the training data licensing matters for commercial use."},
  {"q":"Select ALL rules Day 8 states about AI video in 2026.","type":"multi","options":[{"text":"Keep clips short (5-10 seconds).","correct":true},{"text":"Describe motion explicitly — models default to static.","correct":true},{"text":"Image-to-video is more controllable than text-to-video.","correct":true},{"text":"30-second clips look amazing on free tiers.","correct":false},{"text":"Consistency across shots is trivial.","correct":false}],"explanation":"Short, motion-explicit, image-anchored. Consistency is still hard; 30+ seconds still looks cursed on free tiers."},
  {"q":"What is C2PA and why does Day 8 mention it?","type":"single","options":[{"text":"A python library for face swaps.","correct":false},{"text":"Invisible provenance tags that many platforms embed to mark AI-generated media.","correct":true},{"text":"The certification for AI ethicists.","correct":false},{"text":"A Canva export format.","correct":false}],"explanation":"C2PA is the embedded provenance standard. The point: most platforms tag AI output whether you disclose or not — better to disclose anyway."},
  {"q":"One common mistake: your poster's text comes out garbled. What's Day 8's fix?","type":"single","options":[{"text":"Retry the same prompt 20 times.","correct":false},{"text":"Stop asking Nano Banana/Firefly to render text — generate text-free, then composite in Ideogram or Canva.","correct":true},{"text":"Switch to Midjourney with more adjectives.","correct":false},{"text":"Downgrade to SD 1.5.","correct":false}],"explanation":"Ideogram is the text-rendering champion. Everyone else still garbles. Composite typography separately."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 8;

-- ============================================================================
-- DAY 9 — Transcription, deck-gen, voice, avatars
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Which tool would Day 9 pick for transcribing a PRIVATE interview with a professor about sensitive research?","type":"single","options":[{"text":"Otter.ai cloud recording","correct":false},{"text":"Whisper (open-source, runs locally, private)","correct":true},{"text":"HeyGen","correct":false},{"text":"ElevenLabs","correct":false}],"explanation":"Whisper is MIT-licensed and runs locally — the right tool when the audio is sensitive and can't leave the device."},
  {"q":"Day 9's slide design truths include:","type":"multi","options":[{"text":"One idea per slide; split if two share.","correct":true},{"text":"Max six words per bullet.","correct":true},{"text":"Numbers beat adjectives ('30% faster' > 'much faster').","correct":true},{"text":"More text = more credibility.","correct":false},{"text":"Speaker notes for details; not on-slide text.","correct":true}],"explanation":"AI can generate pretty slides; it can't fix a weak argument. The layout rules still matter."},
  {"q":"When is it ETHICALLY okay to clone a voice in ElevenLabs?","type":"single","options":[{"text":"Anytime, as long as the output is funny.","correct":false},{"text":"Only your own voice, or with explicit consent from the person you're cloning.","correct":true},{"text":"Any celebrity is fair game for satire.","correct":false},{"text":"Only if you pay for Pro tier.","correct":false}],"explanation":"Day 9 is explicit: your voice, or documented consent. Otherwise it's impersonation regardless of platform policy."},
  {"q":"Why does Gamma use an OUTLINE-first workflow rather than a slide-first one?","type":"single","options":[{"text":"Outlines are faster to debug; slides are an output format.","correct":true},{"text":"Gamma can't render slides directly.","correct":false},{"text":"Outlines are a legal requirement in India.","correct":false},{"text":"Slides look worse in dark mode.","correct":false}],"explanation":"Write what you want to say; let Gamma decide slide breaks. The mindset shift is to stop thinking in slides."},
  {"q":"What's the single most common MISTAKE in AI-generated decks that Day 9 flags?","type":"single","options":[{"text":"Using Helvetica","correct":false},{"text":"More than one idea per slide (violating the one-idea rule).","correct":true},{"text":"Embedding videos","correct":false},{"text":"Missing a QR code","correct":false}],"explanation":"Gamma tends to produce 11 slides when you want 5; re-prompt for 'exactly 5 slides, one idea each, 6 words per bullet' rather than manually deleting."},
  {"q":"What should you ALWAYS say at the start of a recorded meeting?","type":"text","options":[],"explanation":"Strong answer: an explicit disclosure that you are recording/transcribing and an invitation to opt out. Both ethics and, in many jurisdictions, the law."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 9;

-- ============================================================================
-- DAY 10 — MILESTONE 1: Capstone ideathon + locked one-pager
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Milestone 1's one-pager must be UNDER how many words?","type":"single","options":[{"text":"200","correct":false},{"text":"400","correct":true},{"text":"1000","correct":false},{"text":"No limit","correct":false}],"explanation":"≤400 words. The constraint forces scope discipline — if you can't say it in 400 words, you don't understand it yet."},
  {"q":"Day 10's 3-filter test for a capstone idea is:","type":"single","options":[{"text":"Is it flashy? Is it new? Will it win awards?","correct":false},{"text":"Real user (can I name one)? Small scope (ship crappy-but-usable in ~10 hours)? You care (still excited in Week 3 at 2am)?","correct":true},{"text":"Is it AI-native? Is it Indian? Is it profitable?","correct":false},{"text":"Is the stack trendy? Is there a tutorial? Is it resume-worthy?","correct":false}],"explanation":"Three yeses = ship. Two = reshape. One or fewer = drop. Named user + small scope + genuine care = capstone survival."},
  {"q":"Why is the 'Non-goals' (won't-build) section the MOST important part of the one-pager?","type":"single","options":[{"text":"It pads the page.","correct":false},{"text":"It pre-commits your future self in Week 3 — when you're tempted to add auth/mobile/analytics, the list says no.","correct":true},{"text":"Graders give extra marks for long non-goals.","correct":false},{"text":"It hides weaknesses from the panel.","correct":false}],"explanation":"Scope creep kills every cohort project. The non-goals line is a gift to your 2am self; if it's shorter than Scope, you haven't committed."},
  {"q":"Day 10 poses the Heilmeier Catechism — nine questions. Select ALL that appear.","type":"multi","options":[{"text":"'What are you trying to do? Articulate with no jargon.'","correct":true},{"text":"'Who cares? If you succeed, what difference does it make?'","correct":true},{"text":"'What are the metrics that matter?'","correct":true},{"text":"'What is your marketing budget?'","correct":false},{"text":"'How is it done today, and what are the limits of current practice?'","correct":true}],"explanation":"Heilmeier's 9 questions are ruthless and short. 'Marketing budget' is not one of them — this is DARPA, not B-school."},
  {"q":"Teams of what size does Day 10 recommend for capstones?","type":"single","options":[{"text":"1-2","correct":false},{"text":"2-3","correct":true},{"text":"4-5","correct":false},{"text":"6+","correct":false}],"explanation":"2-3. Solo is allowed but harder; 4+ moves slower than 2 for this size of project. Pick complementary skills AND matching work rhythms."},
  {"q":"Why does Day 10 insist you name a REAL human user before submitting the one-pager?","type":"single","options":[{"text":"It's a cohort social requirement.","correct":false},{"text":"No named user = no feedback loop = no learning — 'I'll find users later' fails every cohort.","correct":true},{"text":"The user owns 10% of your capstone.","correct":false},{"text":"It's tax-deductible.","correct":false}],"explanation":"Named users turn opinions into evidence. If you can't WhatsApp someone TODAY about your capstone, pick a different idea."},
  {"q":"In one sentence: what is your tripwire for killing or reshaping this capstone by Week 3?","type":"text","options":[],"explanation":"Strong answer names the weakest filter (user, scope, or motivation), a specific observable signal (unreachable user, scope >15 hours, dead motivation), and a pre-committed action with a date."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 10;

-- ============================================================================
-- DAY 11 — Sharpening the problem statement (Heilmeier, 5 Whys, HMW)
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Day 11 asks you to write your problem statement in THREE versions. What are V1, V2, V3?","type":"single","options":[{"text":"V1 Heilmeier long-form (handwritten), V2 150 words, V3 on a sticky note","correct":true},{"text":"V1 tweet, V2 email, V3 essay","correct":false},{"text":"V1 Hindi, V2 English, V3 emoji","correct":false},{"text":"V1 Claude, V2 ChatGPT, V3 Gemini","correct":false}],"explanation":"The shrinkage from v1 to v3 is the product of actual thinking — most capstones drop ~60% in words and gain in clarity."},
  {"q":"The THREE diseases of a vague problem statement, per Day 11, are:","type":"single","options":[{"text":"Solution smuggling, audience blur, success amnesia","correct":true},{"text":"Scope creep, feature creep, timeline creep","correct":false},{"text":"Overfitting, underfitting, leakage","correct":false},{"text":"Hype, fatigue, confusion","correct":false}],"explanation":"Solution smuggling = you already decided. Audience blur = 'users' isn't a person. Success amnesia = can't say what 'worked' looks like in one sentence."},
  {"q":"Why does Day 11 say 'a sharp WRONG statement is infinitely better than a soft possibly-right one'?","type":"single","options":[{"text":"Sharp statements have prettier fonts.","correct":false},{"text":"A sharp statement can be falsified by a Day 13 interview in 20 minutes; a soft one quietly rots.","correct":true},{"text":"Sharp statements are easier to fake.","correct":false},{"text":"Soft statements use more AI tokens.","correct":false}],"explanation":"The point of crispness isn't correctness — it's falsifiability. You want to be wrong FAST."},
  {"q":"Select ALL weasel words Day 11 bans from your problem statement.","type":"multi","options":[{"text":"leverage","correct":true},{"text":"holistic","correct":true},{"text":"seamless","correct":true},{"text":"AI-powered","correct":true},{"text":"users (as opposed to a named person)","correct":true},{"text":"hostel (a specific Indian-campus noun)","correct":false}],"explanation":"All five are banned. Concrete nouns like 'hostel', 'mess secretary', 'final-year CSE student' are welcome."},
  {"q":"The 5 Whys technique is attributed to which company/method?","type":"single","options":[{"text":"McKinsey","correct":false},{"text":"Toyota (lean manufacturing)","correct":true},{"text":"Google","correct":false},{"text":"Apple","correct":false}],"explanation":"Toyota invented it on the factory floor. Ask 'why?' five times in a row to drill from symptom to root cause."},
  {"q":"A good 'How Might We' (HMW) statement has three properties. Which are they?","type":"single","options":[{"text":"Names a specific user, names a specific friction, leaves solution space open","correct":true},{"text":"Uses 'How', 'Might', 'We' as the first three words only","correct":false},{"text":"Is between 10 and 15 words","correct":false},{"text":"Has to rhyme","correct":false}],"explanation":"Specific user + specific friction + open solution space. If the solution is baked in, you're decorating, not ideating."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 11;

-- ============================================================================
-- DAY 12 — Design thinking: the 5-stage loop
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"The five stages of design thinking are:","type":"single","options":[{"text":"Empathize, Define, Ideate, Prototype, Test","correct":true},{"text":"Plan, Do, Check, Act, Repeat","correct":false},{"text":"Research, Draft, Edit, Publish, Promote","correct":false},{"text":"Think, Talk, Type, Tweak, Ship","correct":false}],"explanation":"The five stages. Linear diagrams lie — you bounce between them; the rhythm inside each stage is diverge then converge."},
  {"q":"What is the Point of View (POV) format in the Define stage?","type":"single","options":[{"text":"'I think / I feel / I believe'","correct":false},{"text":"'[specific user] needs [verb-based need] because [surprising insight]'","correct":true},{"text":"'Imagine a world where...'","correct":false},{"text":"'In summary, we will build X.'","correct":false}],"explanation":"If your POV's insight slot reads 'users want it faster,' you've restated the premise, not defined anything."},
  {"q":"Day 12 names three anti-patterns. Select ALL.","type":"multi","options":[{"text":"PowerPoint prototypes (a 40-slide deck is not a prototype)","correct":true},{"text":"Validation theatre (friendly users, friendly answers, fake confirmation)","correct":true},{"text":"Falling in love with stage one (three weeks in Empathize, never shipping)","correct":true},{"text":"Using sticky notes (too old-school)","correct":false}],"explanation":"Sticky notes are fine; theatre is not. These three anti-patterns kill more capstones than bad ideas do."},
  {"q":"Day 12's Ideate rule: how many ideas should you aim for in a 20-minute session?","type":"single","options":[{"text":"3-5","correct":false},{"text":"~10","correct":false},{"text":"30+","correct":true},{"text":"100+","correct":false}],"explanation":"Go wide before going deep. A team that generates 10 ideas and builds the first one isn't ideating — it's defaulting."},
  {"q":"What does Day 12 mean by 'divergent vs convergent thinking'?","type":"single","options":[{"text":"Different personality types arguing","correct":false},{"text":"Diverging = open the funnel and generate many options without judging; converging = close the funnel and cut ruthlessly","correct":true},{"text":"Divergent = Claude; Convergent = GPT","correct":false},{"text":"Divergent = visual; Convergent = textual","correct":false}],"explanation":"The anti-pattern is holding both at once ('yes, but'). Separate them in time: diverge first, then converge."},
  {"q":"Name one 'bad' idea you'd generate using Day 12's forcing constraints (1 sentence).","type":"text","options":[],"explanation":"Strong answer picks one constraint ($1 version / no-screen version / 7-year-old user / offline) and names the principle hidden inside the absurd idea that's actually worth testing."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 12;

-- ============================================================================
-- DAY 13 — User interviews (The Mom Test)
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"The Mom Test's three rules are:","type":"single","options":[{"text":"Lie once, smile twice, nod three times","correct":false},{"text":"Talk about their life not your idea; ask about specifics in the past not generics about the future; talk less listen more","correct":true},{"text":"Record everything; transcribe nothing; summarise yearly","correct":false},{"text":"Always pitch; always follow up; always close","correct":false}],"explanation":"Rob Fitzpatrick's three rules. Even your mom will lie to you about your idea — so ask about their LIFE, never your IDEA."},
  {"q":"Which of these is Mom-Test-COMPLIANT?","type":"single","options":[{"text":"'Would you pay for a tool that does X?'","correct":false},{"text":"'What did you DO the last time X happened?'","correct":true},{"text":"'Do you think OTHER people have this problem?'","correct":false},{"text":"'Would you love an app that solves X?'","correct":false}],"explanation":"Past behaviour from the person in front of you. Anything starting with 'would' is future fantasy."},
  {"q":"Day 13 says 'a meeting without a clear NEXT STEP is a failure.' Select ALL examples of REAL signal.","type":"multi","options":[{"text":"'Can I introduce you to my colleague who has this worse than me?'","correct":true},{"text":"'Sure, send me the beta.' (vague)","correct":false},{"text":"A referral, an intro, 15 minutes booked on their calendar","correct":true},{"text":"'This is such a smart idea!' (compliment)","correct":false},{"text":"They paid ₹100 for early access today","correct":true}],"explanation":"Real signal = they give up something of value (time, reputation, money, access). Compliments are a tax on honesty."},
  {"q":"The JTBD (Jobs To Be Done) format, per Day 13, is:","type":"single","options":[{"text":"'Given X, when Y, then Z'","correct":false},{"text":"'When [situation], I want to [motivation], so I can [outcome]'","correct":true},{"text":"'As a [user], I want [feature], because [reason]'","correct":false},{"text":"'Why / Why not / So what'","correct":false}],"explanation":"Triggering situation + emotional/functional motivation + measurable outcome. The canonical milkshake example is Day 13's framing."},
  {"q":"Three patterns to listen for (what people DON'T say), per Day 13:","type":"single","options":[{"text":"Workarounds, emotion spikes, what they refuse to pay for","correct":true},{"text":"Adjectives, superlatives, catchphrases","correct":false},{"text":"Eye contact, posture, filler words","correct":false},{"text":"Accent, pace, vocabulary","correct":false}],"explanation":"Workarounds are gold (people only build them for real problems). Emotion spikes mark the real pain. Credit cards tell the truth."},
  {"q":"In the Day 13 paired drill, what's the pitching rule during the 20-minute interview?","type":"single","options":[{"text":"Pitch your idea up front.","correct":false},{"text":"Do NOT pitch, demo, or mention your idea — especially in the first half.","correct":true},{"text":"Pitch only if the user asks.","correct":false},{"text":"Pitch in Hindi only.","correct":false}],"explanation":"Your job is to leave more confused than you arrived. If you feel the urge to pitch, ask another past-tense question instead."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 13;

-- ============================================================================
-- DAY 14 — Systems thinking + SCQA pitch
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"In a causal-loop diagram, an arrow labelled '+' means:","type":"single","options":[{"text":"The relationship is positive/good.","correct":false},{"text":"Both variables move in the SAME direction (more A → more B).","correct":true},{"text":"Addition in the math sense.","correct":false},{"text":"An AI-recommended action.","correct":false}],"explanation":"+ = same direction. − = opposite direction. Nothing moral about the sign."},
  {"q":"Per Donella Meadows, which type of leverage point is WEAKEST?","type":"single","options":[{"text":"Paradigms (the ideas that the system's goals come from)","correct":false},{"text":"Parameters (tweaking a number like an inbox limit)","correct":true},{"text":"Goals","correct":false},{"text":"Information flows","correct":false}],"explanation":"Parameters are the easiest lever AND the weakest. Paradigms are hardest AND strongest. Most capstones default to parameter fixes because they feel concrete."},
  {"q":"What does SCQA stand for, in Barbara Minto's framework?","type":"single","options":[{"text":"Situation, Complication, Question, Answer","correct":true},{"text":"State, Context, Quote, Argue","correct":false},{"text":"Story, Character, Quest, Arc","correct":false},{"text":"Setup, Climax, Quiet, Applause","correct":false}],"explanation":"SCQA is the skeleton for any crisp pitch. The Complication must be SURPRISING — usually an insight from your interviews."},
  {"q":"Day 14's pitch delivery has THREE rules. Select ALL.","type":"multi","options":[{"text":"Earn the complication — the insight should surprise a smart listener.","correct":true},{"text":"Name ONE person (not 'users').","correct":true},{"text":"Close with a concrete ask or next step.","correct":true},{"text":"Memorise a 5-minute speech.","correct":false},{"text":"Open with a statistic about AI market size.","correct":false}],"explanation":"Surprise + named person + ask. A pitch ending without an ask is a lecture."},
  {"q":"What's a REINFORCING (R) loop versus a BALANCING (B) loop?","type":"single","options":[{"text":"R amplifies change (vicious or virtuous circle); B stabilises around a goal.","correct":true},{"text":"R is good; B is bad.","correct":false},{"text":"R is Indian; B is British.","correct":false},{"text":"R is research; B is business.","correct":false}],"explanation":"R loops compound (anxiety → checking → more anxiety). B loops self-correct (thermostat)."},
  {"q":"Why does Day 14 insist your CLD contain at least ONE closed loop?","type":"single","options":[{"text":"Teachers like circles.","correct":false},{"text":"If arrows only flow one way from cause to symptom, you've drawn a tree, not a system — you haven't captured the feedback that keeps the problem alive.","correct":true},{"text":"Figma renders loops better.","correct":false},{"text":"Pixar requires it.","correct":false}],"explanation":"A tree is a decomposition; a system has feedback. Ask 'what does the symptom cause?' and follow the arrow back to close a loop."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 14;

-- ============================================================================
-- DAY 15 — MILESTONE 2: 1-day sprint + locked 1-page spec
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Day 15's locked 1-page spec has EIGHT sections. Which is listed as MOST IMPORTANT?","type":"single","options":[{"text":"Target user","correct":false},{"text":"What it does","correct":false},{"text":"What it will NOT do (the anti-scope list)","correct":true},{"text":"Week-by-week plan","correct":false}],"explanation":"'A scope list without a NOT list is a wish list.' For every 'will build' item, name what you are explicitly NOT building."},
  {"q":"What does 'shipped' mean at Day 30, per Day 15?","type":"single","options":[{"text":"Posted on LinkedIn with hashtags.","correct":false},{"text":"A real user who is NOT your cohort-mate completes the core flow on their own device and gives you one honest reaction.","correct":true},{"text":"The repo has a README.","correct":false},{"text":"The domain is purchased.","correct":false}],"explanation":"Write that bar directly into your spec. LinkedIn announcements aren't shipping."},
  {"q":"Day 15's Crazy 8s exercise is:","type":"single","options":[{"text":"Drinking 8 coffees in 8 minutes","correct":false},{"text":"Fold a page into 8 frames; set an 8-minute timer; sketch 8 different UI versions of the core screen","correct":true},{"text":"8 team members vote in 8 seconds","correct":false},{"text":"Running 8 A/B tests","correct":false}],"explanation":"Different sketches > beautiful sketches. Dot-vote the three favourites."},
  {"q":"Which of these is a GOOD 14-day success metric?","type":"single","options":[{"text":"'Validate engagement and delight users.'","correct":false},{"text":"'3 beta users complete the full flow and return at least twice in the following week.'","correct":true},{"text":"'Become the next unicorn.'","correct":false},{"text":"'Everyone loves it.'","correct":false}],"explanation":"A number with a timeframe and a unit — 'N users complete X in Y days.' If you can't name N, X, Y, it's not a metric; it's a hope."},
  {"q":"Select ALL items Day 15 suggests for the NOT-LIST of a capstone.","type":"multi","options":[{"text":"Authentication (hardcode a user)","correct":true},{"text":"Payments (stub it)","correct":true},{"text":"Mobile (desktop only)","correct":true},{"text":"Onboarding flows, admin dashboards, email notifications","correct":true},{"text":"The core feature","correct":false}],"explanation":"Any of these can be added later; none are the capstone's core. Cut them in the spec, not in week 3 panic."},
  {"q":"What does the Day 15 submission require BEYOND the spec PDF and wireframes?","type":"single","options":[{"text":"A Notion link that stays editable.","correct":false},{"text":"A public commitment post with 'I am shipping X to Y by Z' AND 2 cohort reactions before midnight.","correct":true},{"text":"A signed notarised affidavit.","correct":false},{"text":"An NFT of the spec.","correct":false}],"explanation":"Public commitment changes behaviour more than any planning app. The point is that other humans are now watching."},
  {"q":"In one sentence: which feature hurt most to move to your NOT-list, and what did that attachment reveal?","type":"text","options":[],"explanation":"Strong answer names the feature, the emotional pull (cool demo, pet peeve, investor-friendly), and admits the cut honestly. Attachment is usually signal of where you're hiding."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 15;

-- ============================================================================
-- DAY 16 — The four rails: Git, GitHub, localhost, APIs
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Day 16's four rails every AI builder rides on are:","type":"single","options":[{"text":"Git, GitHub, localhost, APIs","correct":true},{"text":"Python, JavaScript, SQL, HTML","correct":false},{"text":"AWS, GCP, Azure, on-prem","correct":false},{"text":"Model, data, compute, budget","correct":false}],"explanation":"Read and clicked, no code written. The vocabulary that stops tutorials from feeling like hieroglyphics."},
  {"q":"The difference between a BRANCH and a FORK, in one line:","type":"single","options":[{"text":"Same thing, different name.","correct":false},{"text":"A branch is a parallel universe of the SAME repo you own; a fork is your COPY of someone else's repo under your account.","correct":true},{"text":"A branch is local; a fork is cloud.","correct":false},{"text":"A branch is free; a fork is paid.","correct":false}],"explanation":"Branches live inside one repo. Forks clone the whole repo into your namespace so you can propose changes via PRs."},
  {"q":"HTTP status code 429 means:","type":"single","options":[{"text":"Not found","correct":false},{"text":"Too Many Requests (rate limit exceeded) — client is hitting the API too fast","correct":true},{"text":"Server exploded","correct":false},{"text":"Unauthorized","correct":false}],"explanation":"429 = client's fault, rate-limited. 500 = server's fault. 401 = bad auth. Know them cold."},
  {"q":"Select ALL that describe `localhost:3000`.","type":"multi","options":[{"text":"Your own laptop acting as a server (127.0.0.1)","correct":true},{"text":"Port 3000 is a 'numbered door' on your machine","correct":true},{"text":"Accessible from the public internet by default","correct":false},{"text":"Common dev-server port (Next.js, React, etc.)","correct":true}],"explanation":"Localhost is private to your machine. The port number picks which process answers (3000 for Next, 11434 for Ollama, 8080 generic)."},
  {"q":"In the Day 16 lab, what are the THREE public APIs you hit in Hoppscotch?","type":"single","options":[{"text":"Twitter, Facebook, Instagram","correct":false},{"text":"OpenLibrary, GitHub, Open-Meteo","correct":true},{"text":"OpenAI, Anthropic, Google","correct":false},{"text":"Google Maps, YouTube, Gmail","correct":false}],"explanation":"All three are free, no-auth-required, and give you different JSON shapes. You also trigger a 429 and a 500 on httpbin.org on purpose."},
  {"q":"What's a PR (Pull Request) in plain English?","type":"text","options":[],"explanation":"Strong answer: 'please merge my branch' — a proposal with a diff attached that maintainers can review, comment on, and merge or reject."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 16;

-- ============================================================================
-- DAY 17 — Local LLMs, prompt variants, evals
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"What is QUANTIZATION, per Day 17?","type":"single","options":[{"text":"The process of counting tokens.","correct":false},{"text":"Compressing model weights to 4 or 8 bits so they fit on your laptop.","correct":true},{"text":"Converting from Celsius to Fahrenheit.","correct":false},{"text":"A type of attention head.","correct":false}],"explanation":"GGUF is the single-file packaged format for quantized models used by Ollama and llama.cpp."},
  {"q":"The Day 17 lab runs THREE prompt variants on a 10-row eval. What are they?","type":"single","options":[{"text":"English, Hindi, Tamil","correct":false},{"text":"Zero-shot, CoT+self-critique, few-shot with 3 examples","correct":true},{"text":"Claude, GPT-4o, Gemini","correct":false},{"text":"Paid, free, trial","correct":false}],"explanation":"Three styles × 10 rows = a real eval. You post win rates per variant to the cohort channel."},
  {"q":"Select ALL tools Day 17 recommends for fast free CLOUD inference.","type":"multi","options":[{"text":"Groq (Llama 3.3 70B @ 750 tok/s)","correct":true},{"text":"HuggingFace Chat","correct":true},{"text":"Google AI Studio (Gemini 2.5 Pro + Flash)","correct":true},{"text":"Your grandma's Pentium III","correct":false}],"explanation":"Cloud inference on free tiers is often FASTER than local, which is why Ollama is demo-only for Day 17."},
  {"q":"What is Langfuse used for in the Day 17 lab?","type":"single","options":[{"text":"Replacing ChatGPT.","correct":false},{"text":"Tracing + logging + scoring every LLM call to measure win rates per prompt variant.","correct":true},{"text":"Sending SMS alerts.","correct":false},{"text":"Hosting your model weights.","correct":false}],"explanation":"Langfuse and LangSmith are the platforms that turn prompting from vibes into measurements."},
  {"q":"Why might a 2B local model be 'shockingly fine' for a capstone task?","type":"single","options":[{"text":"Small models are always better.","correct":false},{"text":"If the task is narrow (summarize, classify, extract) and latency/privacy matter, a quantized 1-3B model runs free on a laptop with acceptable quality.","correct":true},{"text":"Because they can't hallucinate.","correct":false},{"text":"They're trained on more data.","correct":false}],"explanation":"Match model size to task difficulty. Many capstone tasks don't need 70B — they need a 2B model that never rate-limits and doesn't leak data."},
  {"q":"In one sentence: what is an 'eval' and why does Day 17 say it separates builders from tinkerers?","type":"text","options":[],"explanation":"Strong answer: a repeatable test of a prompt against a fixed dataset with automatic scoring. Tinkerers change prompts based on vibes; builders A/B test with numbers."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 17;

-- ============================================================================
-- DAY 18 — RAG: embeddings, vector DBs, GraphRAG
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"What is an EMBEDDING, per Day 18?","type":"single","options":[{"text":"A hidden token inside the model.","correct":false},{"text":"A vector of numbers that captures the MEANING of a piece of text.","correct":true},{"text":"A CSS technique for images.","correct":false},{"text":"An API key format.","correct":false}],"explanation":"Embeddings are coordinates for meaning. Texts with similar meaning end up close in vector space."},
  {"q":"RAG stands for and means:","type":"single","options":[{"text":"Random Access Generation","correct":false},{"text":"Retrieval-Augmented Generation: ingest your docs → retrieve relevant chunks → generate with them in context","correct":true},{"text":"Rapid AI Graphing","correct":false},{"text":"Regex Anchored Grep","correct":false}],"explanation":"RAG gives the LLM access to YOUR data it doesn't have in its weights. Day 18's alternative to bigger models is better retrieval."},
  {"q":"Select ALL knobs you might tune to fix a bad RAG result.","type":"multi","options":[{"text":"Chunk size and overlap","correct":true},{"text":"Embedding model","correct":true},{"text":"Top-K retrieval depth","correct":true},{"text":"The laptop's font size","correct":false},{"text":"Vector store choice (pgvector vs Chroma vs Qdrant)","correct":true}],"explanation":"Bad RAG is almost always a chunk/retrieval/embedding problem before it's a generation problem."},
  {"q":"When would you reach for GraphRAG instead of chunk-based RAG?","type":"single","options":[{"text":"When the corpus is small and flat.","correct":false},{"text":"When the questions require multi-hop reasoning across related entities (who-knows-whom, what-depends-on-what).","correct":true},{"text":"When you want cheaper storage.","correct":false},{"text":"When the LLM doesn't support chunks.","correct":false}],"explanation":"Chunks are great for 'find the passage.' Graphs are better for 'connect entities across documents.'"},
  {"q":"In the Day 18 lab, Neon provides:","type":"single","options":[{"text":"A proprietary LLM.","correct":false},{"text":"A free Postgres with the `vector` extension pre-installed, used for production-shaped pgvector storage.","correct":true},{"text":"A wireframing tool.","correct":false},{"text":"A browser agent.","correct":false}],"explanation":"Neon + pgvector is the 'production-shaped' path; NotebookLM is the zero-code path; LlamaIndex is the middle framework."},
  {"q":"In one sentence: name a document from YOUR life you wish AI 'knew' and the first 5 questions you'd ask it.","type":"text","options":[],"explanation":"Strong answer names a real doc (syllabus, internship report, hostel handbook), lists 5 real questions, and implies that chunk-based RAG over those PDFs would answer them."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 18;

-- ============================================================================
-- DAY 19 — Context engineering: CLAUDE.md + AGENTS.md + slash commands
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"What is CLAUDE.md, per Day 19?","type":"single","options":[{"text":"A README for humans.","correct":false},{"text":"A markdown file Claude Code auto-reads when it opens your project — your AI 'onboarding doc' with persistent rules.","correct":true},{"text":"Anthropic's license file.","correct":false},{"text":"A Claude subscription tier.","correct":false}],"explanation":"If RAG gives the LLM your DATA, CLAUDE.md gives it your project's RULES. The model reads it every session so you stop re-explaining."},
  {"q":"How does AGENTS.md differ from CLAUDE.md?","type":"single","options":[{"text":"They're identical.","correct":false},{"text":"AGENTS.md is vendor-neutral (Codex, Cursor, Aider all read it); CLAUDE.md is Claude-specific.","correct":true},{"text":"AGENTS.md is longer.","correct":false},{"text":"AGENTS.md only works on Linux.","correct":false}],"explanation":"Same idea, wider audience. Most repos now ship both so any harness picks up context."},
  {"q":"Select ALL that belong in a strong CLAUDE.md.","type":"multi","options":[{"text":"Project Overview","correct":true},{"text":"Coding Rules (actionable, testable)","correct":true},{"text":"File Locations + Architecture","correct":true},{"text":"Common Pitfalls","correct":true},{"text":"Personal diary entries","correct":false}],"explanation":"Every rule should be testable. Vague rules ('write good code') train the model on nothing."},
  {"q":"What is a SLASH COMMAND in Claude Code?","type":"single","options":[{"text":"A way to delete files.","correct":false},{"text":"A saved prompt you trigger with `/name` — lives in `.claude/commands/`.","correct":true},{"text":"A keyboard shortcut.","correct":false},{"text":"A type of HTTP method.","correct":false}],"explanation":"Day 19 has you ship `/review`, `/plan`, `/explain` as reusable automations."},
  {"q":"Why does Day 19 say context engineering beats better prompting?","type":"single","options":[{"text":"It doesn't — prompting is always better.","correct":false},{"text":"Load context ONCE, reuse forever. Prompts repeat every conversation; CLAUDE.md persists.","correct":true},{"text":"Context engineering is a paid feature.","correct":false},{"text":"Because Anthropic said so.","correct":false}],"explanation":"The Day 4 table of 'prompt eng vs context eng' reappears here: one-off messages vs a whole information environment."},
  {"q":"In one sentence: which single CLAUDE.md rule will save you the most hours this week?","type":"text","options":[],"explanation":"Strong answer names a SPECIFIC rule tied to a repeated pain — e.g., 'always run the typecheck after edits' or 'never introduce new dependencies without asking first.'"}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 19;

-- ============================================================================
-- DAY 20 — Automation with n8n + browser-use
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Day 20 argues the real AI ROI is:","type":"single","options":[{"text":"Chatting more often.","correct":false},{"text":"Automation: trigger → data fetch → AI step → action.","correct":true},{"text":"Buying Pro subscriptions.","correct":false},{"text":"Posting on LinkedIn.","correct":false}],"explanation":"Chat demos look cool. Automation saves hours per week — which is why ROI is measured in minutes-per-week-saved."},
  {"q":"What is a WEBHOOK?","type":"single","options":[{"text":"A kind of fish.","correct":false},{"text":"A URL that external services POST to when something happens (a form fills, a PR opens, an email arrives).","correct":true},{"text":"A VPN.","correct":false},{"text":"A JavaScript framework.","correct":false}],"explanation":"Webhooks are the 'push' side of integration — they trigger your n8n flow so you don't have to poll."},
  {"q":"When do you reach for browser-use (or Claude computer-use) instead of an API?","type":"single","options":[{"text":"When the target service has a great API.","correct":false},{"text":"When the task is behind a login or there's no API — you need an AI that sees and clicks a real browser like a human.","correct":true},{"text":"When you want to save battery.","correct":false},{"text":"When you want to avoid AI entirely.","correct":false}],"explanation":"Browser agents are the last resort after APIs. They're flakier and slower but reach what APIs can't."},
  {"q":"Select ALL that can act as a TRIGGER for an n8n flow.","type":"multi","options":[{"text":"A cron schedule","correct":true},{"text":"An inbound webhook","correct":true},{"text":"A new email or DB row","correct":true},{"text":"A manual 'Execute' click","correct":true},{"text":"A solar eclipse","correct":false}],"explanation":"Schedule, webhook, app event, or manual — those are the trigger types. The solar eclipse is not supported out of the box."},
  {"q":"What's Firecrawl / Jina Reader for?","type":"single","options":[{"text":"Translating to Hindi.","correct":false},{"text":"'Give me a URL, get back clean markdown' — scraping JS-heavy pages into text for RAG or AI steps.","correct":true},{"text":"Generating images.","correct":false},{"text":"Running local LLMs.","correct":false}],"explanation":"When the source is a web page, these tools normalise HTML into LLM-ready markdown."},
  {"q":"How do you compute the WEEKLY-HOURS-SAVED ROI per Day 20?","type":"text","options":[],"explanation":"Strong answer: minutes-per-task × tasks-per-week ÷ 60 = hours saved. Example: 4 min × 40 tickets × 5 days = 13.3 hrs/week."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 20;

-- ============================================================================
-- DAY 21 — MILESTONE 3: Vibe-coding the capstone v0
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Day 21 is Capstone Milestone 3. What must you submit?","type":"single","options":[{"text":"Just a README.","correct":false},{"text":"A working v0 prototype (live URL or recorded local demo + repo link) + 200-word director's commentary.","correct":true},{"text":"30 pages of design docs.","correct":false},{"text":"A patent filing.","correct":false}],"explanation":"Milestone 3 collides four weeks of context, prompting, RAG, and context engineering into something that RUNS."},
  {"q":"Day 21's core mindset flip is:","type":"single","options":[{"text":"Type more code, faster.","correct":false},{"text":"Director-not-typist — compress intent into English, don't compile English into code.","correct":true},{"text":"Use only Python.","correct":false},{"text":"Avoid all AI tools.","correct":false}],"explanation":"Vibe-coding is directing, not typing. Your CLAUDE.md is the brief; the tool is the worker."},
  {"q":"The 4-part spec you hand a vibe-coding tool is:","type":"single","options":[{"text":"Intro, Body, Conclusion, Appendix","correct":false},{"text":"Context, Invariants, Task, Acceptance","correct":true},{"text":"What, Why, When, Where","correct":false},{"text":"Budget, Timeline, People, Tools","correct":false}],"explanation":"Context = what it is. Invariants = what never breaks. Task = what to do. Acceptance = how you'll know it's done."},
  {"q":"Select ALL when a TIGHT leash is preferable to a LONG leash.","type":"multi","options":[{"text":"Touching production data or payments","correct":true},{"text":"A change you haven't specified acceptance for","correct":true},{"text":"Scaffolding CSS boilerplate","correct":false},{"text":"Core logic in a domain you understand deeply","correct":true}],"explanation":"Long leash = scaffolding, tests, CSS, CRUD. Tight leash = anything irreversible or domain-critical."},
  {"q":"Which tools does Day 21 list as vibe-coding harnesses?","type":"single","options":[{"text":"Cursor, bolt.new, Google Antigravity (primary picks)","correct":true},{"text":"Microsoft Word, Notepad, vim","correct":false},{"text":"Figma, Sketch, Adobe XD","correct":false},{"text":"Excel, Numbers, Google Sheets","correct":false}],"explanation":"Cursor + bolt.new + Antigravity as primary; Claude Code, Cline, Dify demoed. Your Day 19 CLAUDE.md comes along."},
  {"q":"Why should your CLAUDE.md be UPDATED before the Day 21 lab starts?","type":"text","options":[],"explanation":"Strong answer: every bad guess the model makes today traces back to missing or wrong context in CLAUDE.md. Stale context = more re-prompting and worse output."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 21;

-- ============================================================================
-- DAY 22 — Deploy live, cost-per-user, trust UX, llms.txt
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"The cost-per-user formula per Day 22 is:","type":"single","options":[{"text":"interactions × (input_tokens × input_price + output_tokens × output_price), monthly","correct":true},{"text":"revenue minus expenses","correct":false},{"text":"cloud bill divided by team size","correct":false},{"text":"GPU hours × ₹100","correct":false}],"explanation":"Always compute at 10 / 100 / 1000 users. The number that shocks you is usually the system-prompt's token count multiplied out."},
  {"q":"The six elements of Day 22's TRUST STACK are:","type":"single","options":[{"text":"Logo, colors, typography, tagline, hero, footer","correct":false},{"text":"Streaming, uncertainty indicators, citations, stop button, undo, error recovery","correct":true},{"text":"Speed, security, scale, SEO, social, support","correct":false},{"text":"Auth, billing, analytics, logs, monitors, alerts","correct":false}],"explanation":"These six patterns cover most trust failures. The audit: present / partial / missing + one change each."},
  {"q":"What is llms.txt?","type":"single","options":[{"text":"A log file.","correct":false},{"text":"A single markdown file at your domain root that tells LLMs what your site is about — GEO-style metadata for AI crawlers.","correct":true},{"text":"A secret key.","correct":false},{"text":"A prompt-injection payload.","correct":false}],"explanation":"llms.txt + Schema.org JSON-LD make your site citable by ChatGPT / Perplexity / Claude / Gemini in 2026."},
  {"q":"Select ALL platforms Day 22 lists as deployment targets.","type":"multi","options":[{"text":"Vercel","correct":true},{"text":"Fly.io","correct":true},{"text":"Render","correct":true},{"text":"Cloudflare Pages","correct":true},{"text":"Your college FTP server from 2004","correct":false}],"explanation":"Day 22 primary is Vercel + Supabase; reference list includes Fly, Render, Cloudflare Pages/Workers, Netlify, Deno Deploy."},
  {"q":"What is a 'cold start' and why does it matter?","type":"single","options":[{"text":"Morning coffee.","correct":false},{"text":"The first-request latency penalty on serverless platforms — what users judge you on.","correct":true},{"text":"Winter load balancing.","correct":false},{"text":"A type of LLM.","correct":false}],"explanation":"Your first visitor feels the cold start. Pooled connections, warm-up pings, and platform choice all affect it."},
  {"q":"In one sentence: what is GEO (Generative Engine Optimization)?","type":"text","options":[],"explanation":"Strong answer: the craft of getting your site cited by AI search engines (ChatGPT, Perplexity, Claude, Gemini) — llms.txt + Schema.org JSON-LD are the two cheapest wins."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 22;

-- ============================================================================
-- DAY 23 — Agents with tools (ReAct, LangGraph, MCP)
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"The ReAct loop is:","type":"single","options":[{"text":"React + Redux","correct":false},{"text":"Reason + Act: thought → action → observation → repeat","correct":true},{"text":"Retry + Rollback","correct":false},{"text":"Read + Answer","correct":false}],"explanation":"ReAct is the skeleton of modern agents. Thought guides action; observation updates state; repeat until goal or max steps."},
  {"q":"What is MCP (Model Context Protocol), in one line?","type":"single","options":[{"text":"Anthropic's pricing plan.","correct":false},{"text":"The USB-C-style standard for connecting models to tools and data sources.","correct":true},{"text":"A benchmark.","correct":false},{"text":"A quantization format.","correct":false}],"explanation":"MCP is the cable. Filesystem, fetch, Playwright-MCP, and many others plug into Cursor / Claude Desktop uniformly."},
  {"q":"Select ALL five predictable agent break-modes from Day 23.","type":"multi","options":[{"text":"Infinite retry","correct":true},{"text":"Goal drift","correct":true},{"text":"Hallucinated tool","correct":true},{"text":"Context blow-up","correct":true},{"text":"Premature success","correct":true},{"text":"Spontaneous sentience","correct":false}],"explanation":"Know these 5 cold — they're what you fix with loop caps, tool schemas, goal reminders, and chunked context."},
  {"q":"In the Day 23 lab, you build a 3-tool LangGraph agent. The three tools are:","type":"single","options":[{"text":"summarize, translate, classify","correct":false},{"text":"web_search, calculator, write_file","correct":true},{"text":"train, eval, deploy","correct":false},{"text":"git, npm, docker","correct":false}],"explanation":"Those three tools solve the India/Pakistan population-ratio task end-to-end — a real multi-tool loop."},
  {"q":"Why would you write TYPED tool contracts (Pydantic / JSON schema)?","type":"single","options":[{"text":"For looks.","correct":false},{"text":"So the model can't hallucinate arguments — the schema forces valid inputs and the framework rejects invalid ones.","correct":true},{"text":"Because Python requires it.","correct":false},{"text":"For SEO.","correct":false}],"explanation":"Good tool descriptions + typed schemas cut 'hallucinated tool' failures dramatically."},
  {"q":"In one sentence: name one MCP server you'd wire into YOUR capstone and why.","type":"text","options":[],"explanation":"Strong answer names a specific server (filesystem / fetch / Playwright-MCP / a custom one) and the concrete capability it unlocks for the capstone — e.g., 'Playwright-MCP because my flow needs to log into a site with no API.'"}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 23;

-- ============================================================================
-- DAY 24 — Multi-agent orchestration + Claude Skills/Plugins
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Day 24's core claim:","type":"single","options":[{"text":"One bloated agent beats specialized agents.","correct":false},{"text":"Two narrow agents with clear handoffs beat one agent that tries everything.","correct":true},{"text":"Agents should be as large as possible.","correct":false},{"text":"Humans should be removed from the loop.","correct":false}],"explanation":"Separation of concerns works in software and in agent land. Small toolsets, clear inputs/outputs, typed handoffs."},
  {"q":"Match the pattern to its description:","type":"single","options":[{"text":"Supervisor = peer-to-peer handoffs, no boss","correct":false},{"text":"Supervisor = boss agent delegates to workers; Swarm = peer-to-peer handoffs; Hierarchical = nested teams of teams","correct":true},{"text":"Swarm = one agent does it all","correct":false},{"text":"Hierarchical = no structure","correct":false}],"explanation":"Three orchestration patterns. Supervisor is the most common first split."},
  {"q":"What are Claude SKILLS?","type":"single","options":[{"text":"Paid upgrades to Claude.","correct":false},{"text":"Packaged, auto-loaded instruction bundles that teach a Claude agent a specific task.","correct":true},{"text":"Programming languages.","correct":false},{"text":"Voice options.","correct":false}],"explanation":"Skills package behavior; Plugins bundle Skills + commands + hooks + MCP servers as one installable unit."},
  {"q":"Select ALL frameworks Day 24 names for multi-agent workflows.","type":"multi","options":[{"text":"Claude Agent SDK","correct":true},{"text":"OpenAI Swarm","correct":true},{"text":"LangGraph multi-agent","correct":true},{"text":"CrewAI flows","correct":true},{"text":"jQuery","correct":false}],"explanation":"Claude Agent SDK and OpenAI Swarm are the core lab tools; LangGraph/CrewAI/AutoGen are the broader ecosystem."},
  {"q":"What is a HANDOFF in Swarm terms?","type":"single","options":[{"text":"A sports move.","correct":false},{"text":"The function one agent calls to transfer control to another agent with a typed payload.","correct":true},{"text":"A login token.","correct":false},{"text":"A network disconnect.","correct":false}],"explanation":"Clean handoff = specify inputs, outputs, and what must never leak. The payload sketch is today's pre-class homework."},
  {"q":"In one sentence: what two-role split in YOUR capstone would benefit most from going multi-agent?","type":"text","options":[],"explanation":"Strong answer names the split (researcher+writer / planner+coder / intake+responder) and the confusion a single agent was hitting in Day 23 that the split fixes."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 24;

-- ============================================================================
-- DAY 25 — Mini-Demo Day (Ideathon 2) — Week 5 checkpoint
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Day 25's pitch arc is:","type":"single","options":[{"text":"30-sec hook → 2-min story with live demo → 30-sec specific ask","correct":true},{"text":"5-min background → 5-min demo → 5-min Q&A","correct":false},{"text":"1-min elevator pitch","correct":false},{"text":"No structure, wing it","correct":false}],"explanation":"Total 3 min + 1 min Q&A. The ASK should be visible on-slide in case you run out of time."},
  {"q":"Day 25 asks demoers to label each piece of critique as:","type":"single","options":[{"text":"Good / Bad / Ugly","correct":false},{"text":"Signal (specific, real) / Taste (preference) / Confused (communication miss)","correct":true},{"text":"Agree / Disagree / Maybe","correct":false},{"text":"Fix / Ignore / Argue","correct":false}],"explanation":"Each category needs a different response. Signal = fix. Taste = note and move on. Confused = rewrite the pitch."},
  {"q":"Select ALL that belong in Day 25's submission package.","type":"multi","options":[{"text":"Demo recording","correct":true},{"text":"Three peer critiques","correct":true},{"text":"A one-page 'what I will change and what I will NOT' doc","correct":true},{"text":"A patent filing","correct":false}],"explanation":"The 'will NOT change' list is as important as the 'will change' list — it protects you from reactive scope creep."},
  {"q":"Why is Day 25 called 'Ideathon 2'?","type":"single","options":[{"text":"It's the second ideation session.","correct":false},{"text":"It's the Week-5 checkpoint where your v0 probes reality — a deliberate echo of Day 10's Ideathon 1 that LOCKED scope.","correct":true},{"text":"There's an ideathon every day.","correct":false},{"text":"It's a marketing term.","correct":false}],"explanation":"Ideathon 1 locked direction; Ideathon 2 stress-tests execution. The one-page action doc feeds your Week 6 build."},
  {"q":"Why have a Loom backup recording ready even though the live URL is deployed?","type":"single","options":[{"text":"Loom is required by law.","correct":false},{"text":"If the live URL hiccups during your 3-minute window, you keep going with words and roll the Loom — don't die on flaky Wi-Fi.","correct":true},{"text":"Panelists prefer video.","correct":false},{"text":"Loom gives you extra time.","correct":false}],"explanation":"The timer doesn't pause for your deploy. Backup clips for any slow call are a Day 29 best practice too."},
  {"q":"In one sentence: what 'shape-of-problem' question would a strong panelist ask you?","type":"text","options":[],"explanation":"Strong answer: a question that tests whether you understand the USER's problem independent of your solution — e.g., 'How does this user handle the problem today without your tool?'"}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 25;

-- ============================================================================
-- DAY 26 — Red-teaming: ethics as engineering
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"What is PROMPT INJECTION?","type":"single","options":[{"text":"A medical procedure.","correct":false},{"text":"A malicious instruction smuggled into user input or retrieved data that hijacks the model's behavior.","correct":true},{"text":"A caching technique.","correct":false},{"text":"A SQL attack.","correct":false}],"explanation":"Day 26 runs Garak's `promptinject` probes against your capstone. The canonical pattern: 'Ignore previous instructions and…'"},
  {"q":"Day 26's FIVE safety patterns that cover ~80% of real incidents are:","type":"single","options":[{"text":"Monitoring, logging, alerting, paging, postmortem","correct":false},{"text":"Stop button, citations, rate-limit, I/O filter, opt-out","correct":true},{"text":"TLS, SSH, VPN, MFA, FDE","correct":false},{"text":"RLHF, RAG, SFT, DPO, DPR","correct":false}],"explanation":"Five patterns. Cheap to add, high coverage. Day 26's poll asks how many your capstone has today."},
  {"q":"Select ALL red-team categories Day 26's prompt-of-the-day generates.","type":"multi","options":[{"text":"5 prompt-injection payloads","correct":true},{"text":"3 jailbreak attempts","correct":true},{"text":"2 data-exfiltration probes","correct":true},{"text":"1 smiley emoji","correct":false}],"explanation":"Failure mode + one-line mitigation for each. You deliver the fixes with ETAs BEFORE Day 30."},
  {"q":"Which law is India's Digital Personal Data Protection Act?","type":"single","options":[{"text":"EU AI Act","correct":false},{"text":"DPDP (2023) — consent and purpose-limitation for personal data","correct":true},{"text":"NIST AI RMF","correct":false},{"text":"GDPR","correct":false}],"explanation":"Know DPDP for India, EU AI Act for high-risk systems, NIST AI RMF as a framework. One paragraph each; Day 26 has them in one slide."},
  {"q":"Why does Day 26 insist you red-team your OWN capstone before Day 30?","type":"single","options":[{"text":"It's a tradition.","correct":false},{"text":"Every shipped AI product eventually meets a hostile user, a biased dataset, or a regulator. Better to find failure modes now than on stage.","correct":true},{"text":"Panelists give extra points.","correct":false},{"text":"Garak is paid on Day 30.","correct":false}],"explanation":"Red-teaming is the other half of 'ready to ship.' Three failure modes + three fixes + one 'known unsupported use case' line in your README."},
  {"q":"Name ONE 'known unsupported use case' you'd add to YOUR capstone's README (1 sentence).","type":"text","options":[],"explanation":"Strong answer: a specific boundary (e.g., 'This tool does not provide medical advice; consult a licensed practitioner.') that shrinks the attack surface and sets user expectations."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 26;

-- ============================================================================
-- DAY 27 — Benchmarks + model cards
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"What is benchmark CONTAMINATION?","type":"single","options":[{"text":"A food-safety issue.","correct":false},{"text":"When the benchmark leaks into training data so the model 'knows the test' and its scores become misleading.","correct":true},{"text":"A GPU overheating problem.","correct":false},{"text":"A political label.","correct":false}],"explanation":"MMLU is largely saturated partly for this reason. LiveBench is designed to resist contamination with rotating tasks."},
  {"q":"Which benchmark uses blind side-by-side human voting to produce an Elo score?","type":"single","options":[{"text":"MMLU","correct":false},{"text":"LM Arena","correct":true},{"text":"GPQA","correct":false},{"text":"HumanEval","correct":false}],"explanation":"LM Arena = chess-style Elo from pairwise human preference. The best place to run YOUR 5 real prompts side-by-side."},
  {"q":"Day 27's 1-page model card must include:","type":"single","options":[{"text":"A photo of the model","correct":false},{"text":"Primary + fallback model, why, cost per 1k tokens, expected monthly spend","correct":true},{"text":"The CEO's bio","correct":false},{"text":"Training data in full","correct":false}],"explanation":"Plus 5 real capstone prompts run on LM Arena with 2 diffs pasted. The fallback must be wired into CODE, not just the doc."},
  {"q":"Select ALL reasons Day 27 insists the FALLBACK be wired into code, not just docs.","type":"multi","options":[{"text":"If the primary API goes down at 9am on Day 30, 'graceful fallback' must be a one-line config flip.","correct":true},{"text":"Testing the fallback once proves it actually works.","correct":true},{"text":"Production incidents never happen.","correct":false},{"text":"Cost spikes can shift the economics and you need a switch.","correct":true}],"explanation":"Demo day is three days away. A doc-only fallback fails when the stakes are real."},
  {"q":"Why does Day 27 say 'private eval beats leaderboard headline'?","type":"single","options":[{"text":"Leaderboards are fake.","correct":false},{"text":"Public benchmarks test generic tasks; YOUR 5 capstone prompts test YOUR specific use case — and that's the only comparison that matters.","correct":true},{"text":"Leaderboards cost money.","correct":false},{"text":"Private evals are smaller.","correct":false}],"explanation":"A top-10 LM Arena model may still lose on your specific task. Run the 5 prompts yourself."},
  {"q":"In one sentence: name ONE surprise from the LM Arena top-20 (a model tier collapse, an unexpected high ranking).","type":"text","options":[],"explanation":"Strong answer names a specific model and its position (e.g., 'Qwen2.5-72B sits above GPT-4 variants on coding') and why that surprises the student's prior mental model."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 27;

-- ============================================================================
-- DAY 28 — AI signal pipeline (how to stay current)
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Day 28's AI Signal Pipeline has HOW MANY sources covering WHICH channels?","type":"single","options":[{"text":"3 sources — newsletter, podcast, YouTube","correct":false},{"text":"5 sources — 1 newsletter + 1 podcast + 1 YouTube + 1 X list + 1 paper feed","correct":true},{"text":"10 sources, one per weekday","correct":false},{"text":"20 sources across RSS","correct":false}],"explanation":"Five sources, 30-45 min/week, calendar-locked Friday slot. The ceiling is 45 min — not the floor."},
  {"q":"The 3-minute paper skim looks at:","type":"single","options":[{"text":"Abstract only","correct":false},{"text":"Abstract, last figure/table, conclusion","correct":true},{"text":"Every page carefully","correct":false},{"text":"Just the author names","correct":false}],"explanation":"Abstract tells you the claim; last figure/table shows the numbers; conclusion highlights the caveats. Three minutes is plenty for a first filter."},
  {"q":"Select ALL sources Day 28 highlights.","type":"multi","options":[{"text":"HuggingFace Daily Papers","correct":true},{"text":"The Batch (DeepLearning.ai)","correct":true},{"text":"Karpathy's YouTube","correct":true},{"text":"Latent Space / Interconnects","correct":true},{"text":"Your uncle's WhatsApp forwards","correct":false}],"explanation":"Plus Artificial Analysis for quality/price dashboards, arxiv cs.LG for firehose when hunting."},
  {"q":"What's a 'FIREHOSE' source per Day 28?","type":"single","options":[{"text":"A premium feed","correct":false},{"text":"An unfiltered stream (raw arxiv, all of X) — useful when HUNTING a topic, dangerous as a daily habit","correct":true},{"text":"A paid podcast","correct":false},{"text":"A Slack bot","correct":false}],"explanation":"Curated channels compress hours of firehose. Use firehoses intentionally, not continuously."},
  {"q":"The Day 28 lab requires you to create what DURING class — not aspirationally?","type":"single","options":[{"text":"A capstone feature.","correct":false},{"text":"A recurring 30-min 'AI signal' calendar slot (Friday), with all 5 sources actually subscribed/followed/bookmarked TODAY.","correct":true},{"text":"A GitHub repo.","correct":false},{"text":"A blog post.","correct":false}],"explanation":"Calendar-locked beats aspirational. Instructor literally checks that the recurring event exists."},
  {"q":"In one sentence: what's the worst AI-signal habit you're replacing today?","type":"text","options":[],"explanation":"Strong answer names a specific concrete habit with time cost — '30 min of X scrolling at 11pm' or '10 Substack subs I never read' — and what replaces it on the calendar."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 28;

-- ============================================================================
-- DAY 29 — Dress rehearsal + showcase polish
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Day 29's ONE RULE, said out loud:","type":"single","options":[{"text":"'I will add one more feature.'","correct":false},{"text":"'I will NOT add a feature today.'","correct":true},{"text":"'I will refactor everything.'","correct":false},{"text":"'I will switch frameworks.'","correct":false}],"explanation":"Every past cohort that lost a demo lost it because they built until 11pm on Day 29. Polish, don't add."},
  {"q":"What's in the Day 29 submission package?","type":"single","options":[{"text":"Just a Loom link.","correct":false},{"text":"A re-recorded final rehearsal video + live showcase entry with opt-in ON + pre-recorded fallback clips for any API call > 3s.","correct":true},{"text":"The final repo only.","correct":false},{"text":"A LinkedIn post.","correct":false}],"explanation":"Fallback clips for slow calls = one of the most common causes of 'demo went sideways.'"},
  {"q":"Select ALL things Day 29 asks you to do in rehearsal.","type":"multi","options":[{"text":"Two full timed dry-runs","correct":true},{"text":"Watch them back","correct":true},{"text":"Cut filler words and time the hook strictly","correct":true},{"text":"Add three new features mid-rehearsal","correct":false}],"explanation":"Rehearse until it's boring. Then polish the showcase page — URL, screenshot, tagline, opt-in."},
  {"q":"What's the 'bridge-to-key-message' technique?","type":"single","options":[{"text":"A JavaScript framework.","correct":false},{"text":"A rehearsal technique for handling hostile Q&A by bridging from the question to your pre-prepared key message.","correct":true},{"text":"A VPN setting.","correct":false},{"text":"A UI pattern.","correct":false}],"explanation":"Day 29 workshops the one question you're dreading and rehearses a bridge line so you never freeze on stage."},
  {"q":"Day 29 suggests keeping the ASK visible on what, in case you run out of time?","type":"single","options":[{"text":"Your phone lockscreen","correct":false},{"text":"On a slide visible during the demo","correct":true},{"text":"Printed in your hand","correct":false},{"text":"Voice note","correct":false}],"explanation":"If the timer buzzes before you say the ask, the ask still lands. Belt and suspenders."},
  {"q":"In one sentence: what's a feature you WANT to add tomorrow — and the reason you'll resist it today?","type":"text","options":[],"explanation":"Strong answer names the specific feature and the specific risk of adding it on the eve of demo day (regression, deploy break, rehearsal time lost). The point of this question is emotional self-awareness."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 29;

-- ============================================================================
-- DAY 30 — DEMO DAY (graduation milestone)
-- ============================================================================
update public.quizzes
set questions = $json$[
  {"q":"Day 30's live demo format is:","type":"single","options":[{"text":"1 minute pitch, no Q&A","correct":false},{"text":"5-minute panel demo: 4 min demo + 1 min Q&A, with a pre-recorded backup ready","correct":true},{"text":"30-minute lecture","correct":false},{"text":"Pre-recorded only","correct":false}],"explanation":"Live panel, strict clock. Backup Loom ready for hiccups. This is the capstone milestone."},
  {"q":"Select ALL items required in the Day 30 final submission.","type":"multi","options":[{"text":"Live URL","correct":true},{"text":"Repo","correct":true},{"text":"Pitch deck","correct":true},{"text":"30-second teaser","correct":true},{"text":"200-word 'what I'll do next' statement","correct":true},{"text":"A thesis-length PDF","correct":false}],"explanation":"Five artefacts. The 200-word 'next' statement commits your post-cohort direction."},
  {"q":"What is auto-issued when you complete the 30/30 checkpoint?","type":"single","options":[{"text":"A refund","correct":false},{"text":"Your certificate (at /certificate.html)","correct":true},{"text":"A job offer","correct":false},{"text":"A T-shirt","correct":false}],"explanation":"Certificate auto-issues on completion. You also join the alumni channel and show up in the public showcase."},
  {"q":"Day 30's pre-class says 'arrive how many minutes early'?","type":"single","options":[{"text":"2 min","correct":false},{"text":"10 min (seriously — not 2 min)","correct":true},{"text":"30 min","correct":false},{"text":"Just in time","correct":false}],"explanation":"Laptop, charger, water, smile. Live URL tested in a fresh browser on different Wi-Fi if possible."},
  {"q":"The 30-day arc summarised in six beats is:","type":"single","options":[{"text":"Foundations, Exposure, Think&Tell, Dev+AI Build, Build/Ship/Agentic, Launch","correct":true},{"text":"Read, Write, Arithmetic, Test, Graduate, Celebrate","correct":false},{"text":"Bronze, Silver, Gold, Platinum, Diamond, Mythic","correct":false},{"text":"Plan, Design, Build, Deploy, Maintain, Retire","correct":false}],"explanation":"Day 30 recaps the six-week arc; each week builds on the prior. Today ships what Weeks 1-6 taught you."},
  {"q":"In one sentence: hashtag Day 30 posts use to share the showcase on LinkedIn.","type":"single","options":[{"text":"#techbro","correct":false},{"text":"#GnanalyticaAIWorkshop","correct":true},{"text":"#AI","correct":false},{"text":"#DemoDay","correct":false}],"explanation":"Share your showcase link with #GnanalyticaAIWorkshop so cohort alumni and the workshop can amplify you."},
  {"q":"In one sentence: what's your 200-word 'what I'll do next' headline — the specific skill you'll own in 30 post-cohort days?","type":"text","options":[],"explanation":"Strong answer names a specific skill (ship one more real user on the capstone, contribute a PR to the AI repo you forked, run a 10-user beta) with a deadline and a measurable outcome. Confident, specific, no hype."}
]$json$::jsonb
where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number = 30;

commit;
