-- plan-1-assertions.sql
-- Purpose: SQL verification record for Plan 1 (Role Foundations).
-- Applied directly to the ai-workshop project (user opted to skip staging — beta).
--
-- Date applied: 2026-04-24
-- Project: ai-workshop (ref: qvqlpcnvculkrjpkdrwi)
-- Postgres: 17.6 on aarch64-unknown-linux-gnu
-- Admin UUID (for helper testing, Plan 2 will reuse): e714a59e-2e5d-4636-bd96-1b7756d7e37e

-- =============================================================================
-- TASK 1: profiles.staff_roles column + backfill — PASS
-- Migration: 20260424_0000_staff_roles_column.sql
-- =============================================================================

-- (a) All is_admin=true profiles have staff_roles = {admin,trainer}.
--   mismatched = 0  ✅
-- (b) No profile has an out-of-vocab role.
--   bad_rows = 0  ✅
-- (c) Observed role sets (all non-empty):
--   [['admin','trainer']]  (1 admin user backfilled correctly)
--   Total profiles: 55

-- =============================================================================
-- TASK 2: cohort_faculty.college_role column + backfill — PASS
-- Migration: 20260424_0010_cohort_faculty_college_role.sql
-- =============================================================================

-- Pre-flight note: cohort_faculty does NOT have an is_admin column (spec was
-- wrong). It has a legacy `role text` column with values {faculty, ta, lead}.
-- That column is orthogonal to college_role and retained.
--
-- (a) null_rows = 0  ✅
-- (b) college_role distribution:
--     support = 5  (all existing rows backfilled)
-- (c) No duplicate (cohort_id, user_id) pairs  ✅

-- =============================================================================
-- TASK 3: announcements.deleted_at soft-delete column — PASS
-- Migration: 20260424_0020_announcements_soft_delete.sql
-- =============================================================================
-- Note: the earlier draft of this migration included a DO block that would
-- have loosened RLS. Caught by implementer subagent pre-apply, removed.
-- Final migration is strictly additive (column + partial index).
--
-- (a) col_exists = 1  ✅
-- (b) idx_exists = 1 (announcements_active_idx)  ✅
-- (c) soft_deleted = 0  ✅

-- =============================================================================
-- TASK 4: New SQL role helpers — PASS
-- Migration: 20260424_0030_role_helpers.sql
-- =============================================================================
-- Pre-flight corrections applied before running:
--   pod_faculty.user_id  → pod_faculty.faculty_user_id
--   pod_members.user_id  → pod_members.student_user_id
--   Removed cohort_pods join (pod_members already has cohort_id).
--
-- All four functions created:
--   can_grade_submission, college_role_in, executive_cohort_ids, has_staff_role  ✅
--
-- Role-impersonation test (has_staff_role) deferred to browser smoke test,
-- since Supabase SQL editor's auth.uid() context testing requires the JS
-- client. See Task 5 admin-auth.js browser test below.

-- =============================================================================
-- TASK 5: resolveRoles in admin-auth.js
-- =============================================================================
-- Not a SQL step. Browser smoke test required:
--   1. Sign in at index.html as the admin user (uid above).
--   2. Navigate to faculty.html.
--   3. Devtools console:
--        const { supabase } = await import('./assets/supabase.js');
--        const { resolveRoles } = await import('./assets/admin-auth.js');
--        const { data: { user } } = await supabase.auth.getUser();
--        console.log(await resolveRoles(user, null));
--   Expected: staffRoles = Set(['admin','trainer']); collegeRole = null;
--             can.editContent = true; can.grade = true; can.moderateBoard = true.

-- =============================================================================
-- TASK 6: E2E smoke — PENDING (user browser test)
-- =============================================================================
-- TODO(fill in after browser smoke): index.html, admin-home.html, faculty.html,
-- dashboard.html all load with no regressions vs. before Plan 1.
