-- 20260424_0200_reseed_curriculum_from_csv.sql
-- Reseed quizzes, polls, and assignments for the May 2026 cohort (Cohort 01).
-- Targets cohort id 56268633-9e93-4305-af6a-1b622a833d8e (no slug column on cohorts).

begin;

-- 1. Clear old curriculum for this cohort
delete from public.quizzes     where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e';
delete from public.polls       where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e' and day_number is not null;
delete from public.assignments where cohort_id = '56268633-9e93-4305-af6a-1b622a833d8e';

-- 2. Reseed quizzes
insert into public.quizzes (cohort_id, day_number, title, passing_score, questions) values
('56268633-9e93-4305-af6a-1b622a833d8e', 1, 'Day 1 — What AI Is and Isn''t', 70, '[
  {"q":"Which best describes today''s mainstream ''AI''?","type":"single","options":[{"text":"A program that thinks like a human","correct":false},{"text":"Statistical pattern-matching trained on data","correct":true},{"text":"A rules engine written by experts","correct":false},{"text":"A search index over the web","correct":false}],"explanation":"Modern AI is largely statistical: it learns patterns from data rather than reasoning from hand-coded rules."},
  {"q":"Which of these are everyday AI you''ve likely already used? (select all)","type":"multi","options":[{"text":"Email spam filtering","correct":true},{"text":"Maps ETA prediction","correct":true},{"text":"A pocket calculator","correct":false},{"text":"Photo face grouping","correct":true}],"explanation":"Spam filters, ETA models, and face grouping all use ML; a calculator is deterministic arithmetic."},
  {"q":"What is a hallucination in an LLM?","type":"single","options":[{"text":"A model crash","correct":false},{"text":"A confidently stated but false output","correct":true},{"text":"A safety filter trigger","correct":false},{"text":"A long context window","correct":false}],"explanation":"Hallucinations are plausible-sounding outputs that aren''t grounded in fact."},
  {"q":"Which task is AI generally NOT well-suited for today?","type":"single","options":[{"text":"Drafting marketing copy","correct":false},{"text":"Summarising a meeting transcript","correct":false},{"text":"Guaranteeing factual correctness without verification","correct":true},{"text":"Translating between languages","correct":false}],"explanation":"AI can produce confident errors; ground-truth correctness needs human or tool verification."},
  {"q":"Which statements about AI are true? (select all)","type":"multi","options":[{"text":"AI systems can be biased by their training data","correct":true},{"text":"AI always reflects objective truth","correct":false},{"text":"Generative AI can create new content","correct":true},{"text":"AI replaces the need for domain expertise","correct":false}],"explanation":"Bias inheritance and generative ability are real; AI augments — not replaces — domain experts."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 2, 'Day 2 — Inside an LLM', 70, '[
  {"q":"What is a token in an LLM?","type":"single","options":[{"text":"One English word","correct":false},{"text":"A sub-word unit of text","correct":true},{"text":"A single character","correct":false},{"text":"A model parameter","correct":false}],"explanation":"Tokens are sub-word pieces produced by the tokenizer; one token ≈ ~4 chars on average."},
  {"q":"What does the attention mechanism do?","type":"single","options":[{"text":"Compresses the model weights","correct":false},{"text":"Lets each token weight its relationship to other tokens","correct":true},{"text":"Stops the model from hallucinating","correct":false},{"text":"Speeds up tokenization","correct":false}],"explanation":"Attention computes how much each token should ''attend to'' every other token in the context."},
  {"q":"Which are properties of model weights? (select all)","type":"multi","options":[{"text":"Learned during training","correct":true},{"text":"Fixed numbers at inference time","correct":true},{"text":"Updated on every chat","correct":false},{"text":"Stored as tensors","correct":true}],"explanation":"Weights are learned during training and stay frozen at inference unless you fine-tune."},
  {"q":"What is the ''context window''?","type":"single","options":[{"text":"The model''s training corpus","correct":false},{"text":"The maximum tokens the model can process at once","correct":true},{"text":"The UI chat box","correct":false},{"text":"The reasoning depth","correct":false}],"explanation":"Context window = max tokens (input + output) the model can attend to in a single call."},
  {"q":"Does a vanilla LLM remember past conversations across sessions?","type":"single","options":[{"text":"Yes, automatically","correct":false},{"text":"No, unless memory is engineered in","correct":true},{"text":"Only if you pay for it","correct":false},{"text":"Only on weekends","correct":false}],"explanation":"LLMs are stateless per call; ''memory'' is built via stored notes, embeddings, or app-level state."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 3, 'Day 3 — Prompting Guide', 70, '[
  {"q":"What does the C in CREATE prompting stand for?","type":"single","options":[{"text":"Context","correct":true},{"text":"Constraint","correct":false},{"text":"Clarity","correct":false},{"text":"Complete","correct":false}],"explanation":"CREATE = Context, Role, Examples, Action, Tone, End-state."},
  {"q":"Which are valid prompting techniques? (select all)","type":"multi","options":[{"text":"Few-shot examples","correct":true},{"text":"Chain-of-thought","correct":true},{"text":"Structured output schemas","correct":true},{"text":"Random capitalization","correct":false}],"explanation":"Few-shot, CoT, and structured output are core techniques; random caps is noise."},
  {"q":"When is chain-of-thought most useful?","type":"single","options":[{"text":"For one-word answers","correct":false},{"text":"For multi-step reasoning tasks","correct":true},{"text":"For image generation","correct":false},{"text":"To save tokens","correct":false}],"explanation":"CoT shines when the task requires intermediate reasoning steps."},
  {"q":"What does ''structured output'' mean?","type":"single","options":[{"text":"Formatting in markdown","correct":false},{"text":"Constraining the model to a JSON/typed schema","correct":true},{"text":"Replying in bullet points","correct":false},{"text":"Using bold text","correct":false}],"explanation":"Structured output forces the model into a machine-readable shape (JSON schema, typed fields)."},
  {"q":"Few-shot prompting works because…","type":"single","options":[{"text":"It re-trains the model","correct":false},{"text":"It shows the pattern you want via examples","correct":true},{"text":"It adds more weights","correct":false},{"text":"It bypasses safety filters","correct":false}],"explanation":"In-context examples cue the model toward the desired output format and style."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 4, 'Day 4 — Open Source Models & Indian Stack', 70, '[
  {"q":"Which of these is an Indian-origin model family?","type":"single","options":[{"text":"Sarvam","correct":true},{"text":"Mistral","correct":false},{"text":"Llama","correct":false},{"text":"Qwen","correct":false}],"explanation":"Sarvam AI is India-built; Mistral is French, Llama is Meta (US), Qwen is Alibaba (China)."},
  {"q":"Which are open-weight models? (select all)","type":"multi","options":[{"text":"Llama","correct":true},{"text":"Mistral","correct":true},{"text":"Qwen","correct":true},{"text":"GPT-4","correct":false}],"explanation":"Llama, Mistral, and Qwen publish weights; GPT-4 is closed."},
  {"q":"A key advantage of open-source models is…","type":"single","options":[{"text":"Always more accurate than closed ones","correct":false},{"text":"Self-hosting and data control","correct":true},{"text":"Free GPUs","correct":false},{"text":"No licensing required","correct":false}],"explanation":"Open weights let you self-host, audit, and keep data in your own environment; licensing still applies."},
  {"q":"DeepSeek is best known for…","type":"single","options":[{"text":"Image generation","correct":false},{"text":"Strong reasoning models with open weights","correct":true},{"text":"Speech synthesis","correct":false},{"text":"Browser automation","correct":false}],"explanation":"DeepSeek released competitive reasoning models (e.g., DeepSeek-R1) with open weights."},
  {"q":"Why might an Indian startup pick Sarvam or a fine-tuned Llama?","type":"single","options":[{"text":"Better Indic-language coverage and data residency","correct":true},{"text":"It''s the cheapest GPU","correct":false},{"text":"Required by law","correct":false},{"text":"Always faster","correct":false}],"explanation":"Indic-language tuning and on-shore deployment matter for many Indian use cases."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 5, 'Day 5 — Grounded Research with AI', 70, '[
  {"q":"What is the purpose of ''Deep Research'' modes?","type":"single","options":[{"text":"Faster single-shot answers","correct":false},{"text":"Multi-step browsing and synthesis with citations","correct":true},{"text":"Lower API cost","correct":false},{"text":"Image generation","correct":false}],"explanation":"Deep research agents iterate searches, read sources, and produce cited reports."},
  {"q":"Which tools are oriented around grounded research? (select all)","type":"multi","options":[{"text":"NotebookLM","correct":true},{"text":"Perplexity","correct":true},{"text":"Photoshop","correct":false},{"text":"ChatGPT with web search","correct":true}],"explanation":"NotebookLM, Perplexity, and web-grounded ChatGPT all cite sources."},
  {"q":"''Fast'' mode trades… for…","type":"single","options":[{"text":"Cost for accuracy","correct":false},{"text":"Depth for latency","correct":true},{"text":"Memory for tokens","correct":false},{"text":"Safety for speed","correct":false}],"explanation":"Fast modes return quickly with shallower exploration; thinking/deep modes invest more compute."},
  {"q":"Why upload your own PDFs to NotebookLM?","type":"single","options":[{"text":"To train the base model","correct":false},{"text":"To ground answers in your sources","correct":true},{"text":"To bypass rate limits","correct":false},{"text":"To enable image gen","correct":false}],"explanation":"NotebookLM grounds answers in the documents you provide and cites passages."},
  {"q":"A good habit when using research agents:","type":"single","options":[{"text":"Trust everything they cite","correct":false},{"text":"Spot-check at least one primary source","correct":true},{"text":"Disable citations","correct":false},{"text":"Only use one tool","correct":false}],"explanation":"Citations can be wrong or fabricated — always verify the linchpin claims."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 6, 'Day 6 — Capstone M1: Ideathon', 70, '[
  {"q":"A strong capstone idea should primarily start from…","type":"single","options":[{"text":"A cool tech you saw","correct":false},{"text":"A real, painful user problem","correct":true},{"text":"An impressive demo idea","correct":false},{"text":"An available dataset","correct":false}],"explanation":"Problem-first beats tech-first; the tech is in service of the user pain."},
  {"q":"Which are good brainstorming hygiene rules? (select all)","type":"multi","options":[{"text":"Defer judgement","correct":true},{"text":"Quantity over quality (early)","correct":true},{"text":"Build on others'' ideas","correct":true},{"text":"Pick the first idea fast","correct":false}],"explanation":"Classic divergent-thinking rules; convergence comes later."},
  {"q":"Why timebox an ideathon?","type":"single","options":[{"text":"To prevent perfectionism and force convergence","correct":true},{"text":"Because of fatigue","correct":false},{"text":"Tradition","correct":false},{"text":"To reduce notes","correct":false}],"explanation":"Constraints force decisions and surface what actually matters."},
  {"q":"Best first move after an idea lands:","type":"single","options":[{"text":"Start coding","correct":false},{"text":"Talk to a real potential user","correct":true},{"text":"Design the logo","correct":false},{"text":"Open a GitHub repo","correct":false}],"explanation":"Validate with a human before sinking time into building."},
  {"q":"Which research output is most useful for M1?","type":"single","options":[{"text":"A 50-page report","correct":false},{"text":"A one-pager: problem, who, why now, evidence","correct":true},{"text":"A list of competitors only","correct":false},{"text":"A model architecture diagram","correct":false}],"explanation":"A crisp one-pager forces clarity; long reports hide weak thinking."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 7, 'Day 7 — Problem Statements', 70, '[
  {"q":"The Heilmeier Catechism asks first about…","type":"single","options":[{"text":"What you''re trying to do, in plain language","correct":true},{"text":"Your tech stack","correct":false},{"text":"Your team size","correct":false},{"text":"Your funding","correct":false}],"explanation":"Heilmeier #1: ''What are you trying to do? Articulate with no jargon.''"},
  {"q":"5 Whys is best used to…","type":"single","options":[{"text":"Generate ideas","correct":false},{"text":"Drill from a symptom to a root cause","correct":true},{"text":"Estimate cost","correct":false},{"text":"Pick a model","correct":false}],"explanation":"Repeatedly asking ''why'' moves past surface symptoms to underlying causes."},
  {"q":"How Might We statements are useful because… (select all)","type":"multi","options":[{"text":"They reframe problems as solvable","correct":true},{"text":"They invite multiple solutions","correct":true},{"text":"They lock you to one answer","correct":false},{"text":"They keep tone optimistic","correct":true}],"explanation":"HMW opens the solution space without committing to a specific approach."},
  {"q":"A weak problem statement usually…","type":"single","options":[{"text":"Names the user, pain, and context","correct":false},{"text":"Hides the solution inside the problem","correct":true},{"text":"Cites evidence","correct":false},{"text":"Is short","correct":false}],"explanation":"''We need an AI app for X'' is a solution disguised as a problem."},
  {"q":"Heilmeier asks ''What are the risks?'' to…","type":"single","options":[{"text":"Discourage the work","correct":false},{"text":"Force honest mitigation thinking","correct":true},{"text":"Fill the slide","correct":false},{"text":"Reduce scope","correct":false}],"explanation":"Naming risks early surfaces the assumptions that most need testing."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 8, 'Day 8 — Design Thinking', 70, '[
  {"q":"The five stages of design thinking, in order, are:","type":"single","options":[{"text":"Empathize, Define, Ideate, Prototype, Test","correct":true},{"text":"Plan, Build, Ship, Sell, Repeat","correct":false},{"text":"Research, Design, Code, QA, Launch","correct":false},{"text":"Listen, Pitch, Build, Test, Iterate","correct":false}],"explanation":"The d.school five-stage loop: Empathize → Define → Ideate → Prototype → Test."},
  {"q":"Which are valid Empathize-stage activities? (select all)","type":"multi","options":[{"text":"User interviews","correct":true},{"text":"Shadowing","correct":true},{"text":"Writing the final spec","correct":false},{"text":"Observation","correct":true}],"explanation":"Empathize is about absorbing context; speccing comes later."},
  {"q":"Why prototype early?","type":"single","options":[{"text":"Looks impressive","correct":false},{"text":"Cheapest way to learn what works","correct":true},{"text":"Required by clients","correct":false},{"text":"Replaces user research","correct":false}],"explanation":"A scrappy prototype produces real user feedback faster than perfect design."},
  {"q":"''Define'' produces…","type":"single","options":[{"text":"A point-of-view problem statement","correct":true},{"text":"A working app","correct":false},{"text":"A pricing model","correct":false},{"text":"A signed contract","correct":false}],"explanation":"Define synthesises empathy data into a sharp POV / problem statement."},
  {"q":"Design thinking is best described as…","type":"single","options":[{"text":"A linear waterfall","correct":false},{"text":"An iterative loop you revisit","correct":true},{"text":"A documentation method","correct":false},{"text":"A coding pattern","correct":false}],"explanation":"You loop back as you learn — define-test-redefine repeatedly."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 9, 'Day 9 — User Interviews & The Mom Test', 70, '[
  {"q":"The Mom Test''s core advice is to…","type":"single","options":[{"text":"Ask about specific past behaviour, not opinions on your idea","correct":true},{"text":"Always pitch first","correct":false},{"text":"Send a survey","correct":false},{"text":"Avoid talking to mom","correct":false}],"explanation":"Behaviour and stories are signal; opinions about your idea are noise."},
  {"q":"Which questions are good Mom-Test style? (select all)","type":"multi","options":[{"text":"Tell me about the last time you faced X","correct":true},{"text":"Would you use my app?","correct":false},{"text":"What do you currently do instead?","correct":true},{"text":"How do you handle this today?","correct":true}],"explanation":"Past-tense, behaviour-focused questions yield real data."},
  {"q":"JTBD stands for…","type":"single","options":[{"text":"Jobs To Be Done","correct":true},{"text":"Just Try Building Designs","correct":false},{"text":"Joint Task Backlog Doc","correct":false},{"text":"Journey, Tasks, Behaviour, Data","correct":false}],"explanation":"JTBD frames products as ''hired'' to do a specific job for the user."},
  {"q":"A good interview ratio is roughly…","type":"single","options":[{"text":"You talk 80%","correct":false},{"text":"User talks 80%","correct":true},{"text":"50/50 always","correct":false},{"text":"Doesn''t matter","correct":false}],"explanation":"Listen more than you speak; your job is to learn, not pitch."},
  {"q":"What do you do with compliments in user interviews?","type":"single","options":[{"text":"Bank them as validation","correct":false},{"text":"Discount them and dig for behaviour","correct":true},{"text":"Quote in pitch decks","correct":false},{"text":"Ignore the user","correct":false}],"explanation":"Compliments are polite; they don''t predict purchase or use."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 10, 'Day 10 — Systems Thinking', 70, '[
  {"q":"A causal loop diagram captures…","type":"single","options":[{"text":"UI flows","correct":false},{"text":"Reinforcing and balancing feedback between variables","correct":true},{"text":"Sprint plans","correct":false},{"text":"Data schemas","correct":false}],"explanation":"CLDs show how variables influence each other through feedback loops."},
  {"q":"In Donella Meadows''s framework, which is a high-leverage point?","type":"single","options":[{"text":"Constants and parameters","correct":false},{"text":"Paradigms / mindsets","correct":true},{"text":"Material flows","correct":false},{"text":"Buffer sizes","correct":false}],"explanation":"Mindsets sit near the top of the leverage hierarchy; tweaking constants is low-leverage."},
  {"q":"SCQA stands for…","type":"single","options":[{"text":"Situation, Complication, Question, Answer","correct":true},{"text":"Story, Context, Quote, Action","correct":false},{"text":"Scope, Cost, Quality, Audit","correct":false},{"text":"System, Cause, Query, Analysis","correct":false}],"explanation":"SCQA is Minto''s narrative pattern for structured executive communication."},
  {"q":"Mind maps are best used to… (select all)","type":"multi","options":[{"text":"Branch ideas around a central concept","correct":true},{"text":"Surface relationships","correct":true},{"text":"Replace databases","correct":false},{"text":"Brainstorm visually","correct":true}],"explanation":"Mind maps externalise relationships and aid divergent thinking."},
  {"q":"A reinforcing loop tends to…","type":"single","options":[{"text":"Stabilise the system","correct":false},{"text":"Amplify change in the same direction","correct":true},{"text":"Cancel itself out","correct":false},{"text":"Slow over time","correct":false}],"explanation":"R-loops compound; B-loops counter and stabilise."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 11, 'Day 11 — Capstone M2: Idea Lock', 70, '[
  {"q":"At Idea Lock, what should be settled?","type":"single","options":[{"text":"Final UI colours","correct":false},{"text":"Problem, target user, and core value","correct":true},{"text":"Hosting provider","correct":false},{"text":"Domain name","correct":false}],"explanation":"M2 locks problem-user-value so the rest of the build has a north star."},
  {"q":"A feature is worth building if… (select all)","type":"multi","options":[{"text":"It serves the locked problem","correct":true},{"text":"You can ship a v1 in scope","correct":true},{"text":"It looks impressive in a demo","correct":false},{"text":"A real user would notice if it was missing","correct":true}],"explanation":"Tie features to problem fit and shippability, not demo gloss."},
  {"q":"Where does AI typically add the most value early?","type":"single","options":[{"text":"As a thin chrome over a non-existent product","correct":false},{"text":"Automating a painful, repetitive step","correct":true},{"text":"Replacing the entire backend","correct":false},{"text":"As a marketing gimmick","correct":false}],"explanation":"AI shines when it removes specific drudgery; treat it as a sharp tool, not the whole house."},
  {"q":"Scope-creep guard for M2:","type":"single","options":[{"text":"Add every cool idea","correct":false},{"text":"Maintain a ''later'' list and protect the v1 cut","correct":true},{"text":"Skip prioritisation","correct":false},{"text":"Aim for parity with leaders","correct":false}],"explanation":"A parking-lot for ideas keeps you honest about what ships now vs later."},
  {"q":"Best evidence that your locked idea is real:","type":"single","options":[{"text":"You like it","correct":false},{"text":"Multiple potential users describe the same pain","correct":true},{"text":"It''s on a trending list","correct":false},{"text":"GPT said it''s good","correct":false}],"explanation":"Convergent user pain across interviews is the strongest early signal."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 12, 'Day 12 — Text2Image', 70, '[
  {"q":"Which of these are text-to-image systems? (select all)","type":"multi","options":[{"text":"Stable Diffusion","correct":true},{"text":"Adobe Firefly","correct":true},{"text":"Nano Banana","correct":true},{"text":"Excel","correct":false}],"explanation":"All listed are image-generation tools; Excel isn''t."},
  {"q":"What does ''seed'' control in image generation?","type":"single","options":[{"text":"Image resolution","correct":false},{"text":"Reproducibility of the random sampling","correct":true},{"text":"Color palette","correct":false},{"text":"Watermarking","correct":false}],"explanation":"Same seed + same prompt + same model ≈ same image; useful for iteration."},
  {"q":"Negative prompts are used to…","type":"single","options":[{"text":"Make outputs sad","correct":false},{"text":"Steer the model away from unwanted features","correct":true},{"text":"Reduce file size","correct":false},{"text":"Disable safety","correct":false}],"explanation":"Negative prompts tell the model what not to include (e.g., ''blurry, extra fingers'')."},
  {"q":"Why does aspect ratio matter?","type":"single","options":[{"text":"It changes which compositions the model produces","correct":true},{"text":"It only affects file size","correct":false},{"text":"It''s purely cosmetic","correct":false},{"text":"It changes seed","correct":false}],"explanation":"Models bias to compositions seen at training resolutions; aspect strongly shapes output."},
  {"q":"For commercial use, you should always check…","type":"single","options":[{"text":"Pixel count","correct":false},{"text":"Model and platform licensing terms","correct":true},{"text":"GPU vendor","correct":false},{"text":"Browser","correct":false}],"explanation":"Each tool has its own commercial-use rules; don''t assume."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 13, 'Day 13 — Workflow & Browser Automation', 70, '[
  {"q":"n8n and Zapier are primarily…","type":"single","options":[{"text":"Image editors","correct":false},{"text":"Workflow automation platforms","correct":true},{"text":"Databases","correct":false},{"text":"Code editors","correct":false}],"explanation":"They connect apps via triggers and actions to automate workflows."},
  {"q":"Firecrawl is best described as…","type":"single","options":[{"text":"A CSS framework","correct":false},{"text":"A web crawler/scraper API tuned for LLMs","correct":true},{"text":"A vector DB","correct":false},{"text":"A login provider","correct":false}],"explanation":"Firecrawl turns websites into LLM-ready content via crawling and extraction."},
  {"q":"Which are good automation candidates? (select all)","type":"multi","options":[{"text":"Repetitive copy-paste between tools","correct":true},{"text":"High-volume notifications","correct":true},{"text":"Rare, judgement-heavy decisions","correct":false},{"text":"Scheduled report generation","correct":true}],"explanation":"Repetitive, rule-based, high-frequency tasks pay back; rare nuanced calls don''t."},
  {"q":"A common failure mode of long automations:","type":"single","options":[{"text":"Run too fast","correct":false},{"text":"Silent breakage when an upstream API changes","correct":true},{"text":"Use too few nodes","correct":false},{"text":"Take no inputs","correct":false}],"explanation":"Without monitoring/alerts, automations can silently rot when integrations change."},
  {"q":"Browser automation differs from API automation in that…","type":"single","options":[{"text":"It''s always faster","correct":false},{"text":"It drives a real browser when no API exists","correct":true},{"text":"It''s the same thing","correct":false},{"text":"It only works on Chrome","correct":false}],"explanation":"Browser automation simulates a user; useful when only a UI exists, but more brittle."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 14, 'Day 14 — AI Presentations', 70, '[
  {"q":"Which tools generate slide decks from prompts? (select all)","type":"multi","options":[{"text":"Gamma","correct":true},{"text":"Canva (Magic Design)","correct":true},{"text":"Kimi","correct":true},{"text":"Notepad","correct":false}],"explanation":"Gamma, Canva, and Kimi all have AI deck generation; Notepad does not."},
  {"q":"A good AI-generated deck still requires…","type":"single","options":[{"text":"Nothing — ship as-is","correct":false},{"text":"Human editing for narrative and accuracy","correct":true},{"text":"A new template each time","correct":false},{"text":"Manual recoloring only","correct":false}],"explanation":"AI gives a strong starting draft; the story arc and facts need human ownership."},
  {"q":"Which slide habit is generally best?","type":"single","options":[{"text":"One idea per slide","correct":true},{"text":"Wall of text","correct":false},{"text":"All-image, no labels","correct":false},{"text":"Fifteen bullets","correct":false}],"explanation":"One clear idea per slide keeps cognitive load low and pacing strong."},
  {"q":"For pitch decks, the opener should…","type":"single","options":[{"text":"List your team biographies","correct":false},{"text":"Anchor the audience in the problem","correct":true},{"text":"Show the org chart","correct":false},{"text":"Explain your tech stack","correct":false}],"explanation":"Open with the pain — earn the right to talk about your solution."},
  {"q":"Why export key slides as images for fallback?","type":"single","options":[{"text":"Smaller files","correct":false},{"text":"Robustness when live tools fail at demo time","correct":true},{"text":"SEO","correct":false},{"text":"It''s mandatory","correct":false}],"explanation":"Demos break; static fallbacks save the talk."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 15, 'Day 15 — Vibe Coding', 70, '[
  {"q":"''Vibe coding'' is best described as…","type":"single","options":[{"text":"Coding without testing","correct":false},{"text":"Steering an AI coder toward an outcome with intent and feedback","correct":true},{"text":"Live-streaming code","correct":false},{"text":"Pair programming","correct":false}],"explanation":"You describe intent, the AI drafts, you steer; you stay the editor-in-chief."},
  {"q":"Which tools are AI coding assistants? (select all)","type":"multi","options":[{"text":"Cursor","correct":true},{"text":"Antigravity","correct":true},{"text":"Microsoft Word","correct":false},{"text":"Claude Code","correct":true}],"explanation":"Cursor, Antigravity, and Claude Code are AI dev tools."},
  {"q":"What is ''Plan mode'' useful for?","type":"single","options":[{"text":"Skipping reviews","correct":false},{"text":"Reviewing the AI''s plan before it edits files","correct":true},{"text":"Disabling tests","correct":false},{"text":"Auto-deploying","correct":false}],"explanation":"Plan mode shows the proposed change set so you can adjust before execution."},
  {"q":"Best habit when accepting AI code:","type":"single","options":[{"text":"Always accept blindly","correct":false},{"text":"Read the diff and run it","correct":true},{"text":"Trust the model","correct":false},{"text":"Delete tests it touches","correct":false}],"explanation":"Always read diffs; the model can confidently break things."},
  {"q":"Vibe coding is risky when…","type":"single","options":[{"text":"You skip understanding what was generated","correct":true},{"text":"You keep tests passing","correct":false},{"text":"You commit small steps","correct":false},{"text":"You read the code","correct":false}],"explanation":"Accepting code you can''t maintain is the failure mode."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 16, 'Day 16 — Capstone M3: Mini Demo', 70, '[
  {"q":"A v1 mini demo should prioritise…","type":"single","options":[{"text":"All features partially working","correct":false},{"text":"One end-to-end flow that actually works","correct":true},{"text":"Full visual polish","correct":false},{"text":"A custom domain","correct":false}],"explanation":"One working flow tells a story; a half-built ten beats nothing."},
  {"q":"Pitch structure tips: (select all)","type":"multi","options":[{"text":"Start with the user pain","correct":true},{"text":"Show the demo, not just slides","correct":true},{"text":"Bury the ask","correct":false},{"text":"Time-box every slide","correct":true}],"explanation":"Pain-first, demo-led, clear ask, tight pacing."},
  {"q":"For demo reliability you should…","type":"single","options":[{"text":"Demo live with no fallback","correct":false},{"text":"Have a recorded video as backup","correct":true},{"text":"Use a flaky network on purpose","correct":false},{"text":"Skip rehearsal","correct":false}],"explanation":"Always carry a recording; live demos fail at the worst times."},
  {"q":"After M3, the most useful feedback is…","type":"single","options":[{"text":"Compliments","correct":false},{"text":"Where the demo confused or lost the audience","correct":true},{"text":"Logo opinions","correct":false},{"text":"Font preferences","correct":false}],"explanation":"Confusion points map directly to your next iteration."},
  {"q":"Common M3 anti-pattern:","type":"single","options":[{"text":"Demoing screens that don''t actually run","correct":true},{"text":"Showing real data","correct":false},{"text":"Telling a tight story","correct":false},{"text":"Practising twice","correct":false}],"explanation":"Hand-wavy mockups passed off as ''working'' kills credibility."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 17, 'Day 17 — Git, GitHub, localhost, APIs', 70, '[
  {"q":"What does ''git commit'' do?","type":"single","options":[{"text":"Pushes to GitHub","correct":false},{"text":"Records a snapshot of staged changes locally","correct":true},{"text":"Merges branches","correct":false},{"text":"Deploys the app","correct":false}],"explanation":"Commit is local; push sends commits to a remote like GitHub."},
  {"q":"Which are valid git operations? (select all)","type":"multi","options":[{"text":"branch","correct":true},{"text":"merge","correct":true},{"text":"rebase","correct":true},{"text":"compile","correct":false}],"explanation":"Compile is a build step, not a git operation."},
  {"q":"localhost typically refers to…","type":"single","options":[{"text":"Your own machine via 127.0.0.1","correct":true},{"text":"A cloud server","correct":false},{"text":"GitHub","correct":false},{"text":"A CDN","correct":false}],"explanation":"localhost = the loopback address pointing at your own computer."},
  {"q":"A REST API endpoint usually exposes…","type":"single","options":[{"text":"A web page","correct":false},{"text":"A URL + method that returns/accepts data","correct":true},{"text":"A database directly","correct":false},{"text":"A binary file","correct":false}],"explanation":"REST APIs expose resources via URLs and HTTP verbs (GET, POST, ...)."},
  {"q":"Why use environment variables for API keys?","type":"single","options":[{"text":"They''re shorter","correct":false},{"text":"To keep secrets out of source control","correct":true},{"text":"Required by Git","correct":false},{"text":"They run faster","correct":false}],"explanation":"Env vars keep credentials out of repos and let configs change per environment."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 18, 'Day 18 — Deployment with Vercel and Supabase', 70, '[
  {"q":"Vercel is primarily for…","type":"single","options":[{"text":"Hosting Postgres","correct":false},{"text":"Deploying frontends and serverless functions","correct":true},{"text":"Image editing","correct":false},{"text":"Email","correct":false}],"explanation":"Vercel hosts web frontends and edge/serverless functions; Supabase covers DB/auth."},
  {"q":"Supabase provides… (select all)","type":"multi","options":[{"text":"Postgres database","correct":true},{"text":"Auth","correct":true},{"text":"Edge Functions","correct":true},{"text":"Photo retouching","correct":false}],"explanation":"DB, Auth, Storage, Edge Functions, Realtime — but not photo retouching."},
  {"q":"Why are environment variables critical at deploy time?","type":"single","options":[{"text":"They make builds faster","correct":false},{"text":"They configure secrets per environment","correct":true},{"text":"They format code","correct":false},{"text":"They replace tests","correct":false}],"explanation":"Different environments (dev/preview/prod) need different keys and URLs."},
  {"q":"What does Row-Level Security do?","type":"single","options":[{"text":"Encrypts disks","correct":false},{"text":"Restricts which rows a role can read/write","correct":true},{"text":"Speeds up queries","correct":false},{"text":"Renames columns","correct":false}],"explanation":"RLS policies enforce per-row access in the database itself."},
  {"q":"A typical deploy pipeline:","type":"single","options":[{"text":"Code → push → CI build → deploy","correct":true},{"text":"Code → email → manual upload","correct":false},{"text":"Code → screenshot → ship","correct":false},{"text":"Code → demo → forget","correct":false}],"explanation":"Push triggers CI which builds and deploys; rollback is one revert away."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 19, 'Day 19 — Embeddings & RAG', 70, '[
  {"q":"What is an embedding?","type":"single","options":[{"text":"A compressed image","correct":false},{"text":"A vector representation capturing semantic meaning","correct":true},{"text":"A SQL view","correct":false},{"text":"A type of prompt","correct":false}],"explanation":"Embeddings map text/images into vectors where similarity = closeness."},
  {"q":"RAG stands for…","type":"single","options":[{"text":"Retrieval-Augmented Generation","correct":true},{"text":"Random Access Graph","correct":false},{"text":"Recursive Agent Gateway","correct":false},{"text":"Retrieval Across Graphs","correct":false}],"explanation":"RAG retrieves relevant context, then asks the LLM to generate using it."},
  {"q":"When should you prefer RAG over fine-tuning? (select all)","type":"multi","options":[{"text":"Knowledge changes frequently","correct":true},{"text":"You need source citations","correct":true},{"text":"You need a baked-in writing style","correct":false},{"text":"Data is large and updated daily","correct":true}],"explanation":"RAG handles fresh, citable knowledge; fine-tune for stable style/behaviour."},
  {"q":"A vector DB is used to…","type":"single","options":[{"text":"Store images","correct":false},{"text":"Index and search embeddings by similarity","correct":true},{"text":"Replace Postgres always","correct":false},{"text":"Run prompts","correct":false}],"explanation":"Vector DBs (or pgvector) do nearest-neighbour search over embeddings."},
  {"q":"A common RAG failure is…","type":"single","options":[{"text":"Retrieving the wrong chunks","correct":true},{"text":"Too few tokens","correct":false},{"text":"Embeddings being colourful","correct":false},{"text":"Using JSON","correct":false}],"explanation":"Garbage retrieval ⇒ garbage answers; chunking and ranking matter a lot."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 20, 'Day 20 — Context Engineering: CLAUDE.md & Skills', 70, '[
  {"q":"CLAUDE.md / AGENTS.md files are used to…","type":"single","options":[{"text":"Store secrets","correct":false},{"text":"Give the AI persistent project-specific guidance","correct":true},{"text":"Replace tests","correct":false},{"text":"Bypass auth","correct":false}],"explanation":"They act as ''always-on'' instructions the agent reads each session."},
  {"q":"Good things to put in a project CLAUDE.md: (select all)","type":"multi","options":[{"text":"Architecture quirks","correct":true},{"text":"Conventions","correct":true},{"text":"Your password","correct":false},{"text":"Common commands","correct":true}],"explanation":"Document what isn''t obvious; never store secrets in repo files."},
  {"q":"Rules vs Skills — which is true?","type":"single","options":[{"text":"Rules are reusable workflows; Skills are stricter constraints","correct":false},{"text":"Skills are reusable capabilities; Rules are policy/style constraints","correct":true},{"text":"They''re identical","correct":false},{"text":"Neither exists","correct":false}],"explanation":"Skills package capabilities; rules act as guardrails or style guides."},
  {"q":"Why version-control your AI context files?","type":"single","options":[{"text":"To share them with the team and review changes","correct":true},{"text":"For SEO","correct":false},{"text":"They are required by law","correct":false},{"text":"To make builds slower","correct":false}],"explanation":"Treat AI context as code: review, diff, and roll back like any other config."},
  {"q":"A good context file is…","type":"single","options":[{"text":"As long as possible","correct":false},{"text":"Short, specific, and high-signal","correct":true},{"text":"A copy of all docs","correct":false},{"text":"Random","correct":false}],"explanation":"Context windows are finite; signal density beats volume."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 21, 'Day 21 — Capstone M4: Workspace & First Deploy', 70, '[
  {"q":"For M4, your repo should have…","type":"single","options":[{"text":"Only main branch with secrets","correct":false},{"text":"README, env example, and a deployable build","correct":true},{"text":"Just notebooks","correct":false},{"text":"No history","correct":false}],"explanation":"A new contributor (or future you) should be able to clone and run."},
  {"q":"Things to verify on your first deploy: (select all)","type":"multi","options":[{"text":"Production env vars set","correct":true},{"text":"Auth flows work","correct":true},{"text":"Logs are visible","correct":true},{"text":"Search engine ranking","correct":false}],"explanation":"SEO is a later concern; correctness, auth, and observability come first."},
  {"q":"The fastest path to a real deploy is usually…","type":"single","options":[{"text":"Building your own cloud","correct":false},{"text":"Using managed services (Vercel + Supabase)","correct":true},{"text":"Bare-metal Linux","correct":false},{"text":"Email PDFs","correct":false}],"explanation":"Managed PaaS removes weeks of plumbing; you can always migrate later."},
  {"q":"A .env.example file should…","type":"single","options":[{"text":"Contain real secrets","correct":false},{"text":"List required variables with placeholder values","correct":true},{"text":"Be deleted from repo","correct":false},{"text":"Be encrypted","correct":false}],"explanation":"It documents what to set without exposing real values."},
  {"q":"After first deploy, the next-best move is…","type":"single","options":[{"text":"Rebuild from scratch","correct":false},{"text":"Wire up basic monitoring/error reporting","correct":true},{"text":"Skip user testing","correct":false},{"text":"Stop committing","correct":false}],"explanation":"You can''t fix what you can''t see; observability is foundational."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 22, 'Day 22 — Agentic AI', 70, '[
  {"q":"ReAct combines…","type":"single","options":[{"text":"React (UI) and JavaScript","correct":false},{"text":"Reasoning + Acting (tool use) in a loop","correct":true},{"text":"Retrieval and CSS","correct":false},{"text":"Recurrent + Attention","correct":false}],"explanation":"ReAct interleaves thoughts and tool actions to solve tasks."},
  {"q":"Which are agent frameworks/protocols? (select all)","type":"multi","options":[{"text":"LangGraph","correct":true},{"text":"MCP","correct":true},{"text":"Multi-Agent systems","correct":true},{"text":"Bootstrap","correct":false}],"explanation":"LangGraph orchestrates agents; MCP standardises tool/context interop."},
  {"q":"MCP stands for…","type":"single","options":[{"text":"Model Context Protocol","correct":true},{"text":"Multi-Component Pipeline","correct":false},{"text":"Managed Cloud Platform","correct":false},{"text":"Memory Cache Pattern","correct":false}],"explanation":"MCP standardises how tools/data sources plug into LLM clients."},
  {"q":"A common multi-agent failure mode is…","type":"single","options":[{"text":"Agents loop or talk past each other","correct":true},{"text":"Too cheap","correct":false},{"text":"Too deterministic","correct":false},{"text":"Missing GPU","correct":false}],"explanation":"Without structure (memory, roles, stop conditions), agents drift or loop."},
  {"q":"Tool use is most useful when…","type":"single","options":[{"text":"The model already knows the answer","correct":false},{"text":"You need fresh data, computation, or side effects","correct":true},{"text":"You want shorter prompts","correct":false},{"text":"You want lower cost always","correct":false}],"explanation":"Tools extend models past their parametric knowledge into the real world."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 23, 'Day 23 — AI Cost Estimation', 70, '[
  {"q":"LLM API cost is most directly driven by…","type":"single","options":[{"text":"Number of users","correct":false},{"text":"Tokens in + tokens out","correct":true},{"text":"Number of files","correct":false},{"text":"Time of day","correct":false}],"explanation":"Most providers price per-token (input and output, often different rates)."},
  {"q":"Which actions reduce cost? (select all)","type":"multi","options":[{"text":"Caching responses","correct":true},{"text":"Trimming prompts","correct":true},{"text":"Choosing smaller models when sufficient","correct":true},{"text":"Re-prompting blindly on errors","correct":false}],"explanation":"Cache, compress prompts, right-size models; retries multiply spend."},
  {"q":"What is a knowledge graph good for in cost terms?","type":"single","options":[{"text":"Reducing repeated retrieval/computation by structuring relationships","correct":true},{"text":"Always cheaper than RAG","correct":false},{"text":"Replacing the model","correct":false},{"text":"Free GPUs","correct":false}],"explanation":"KGs encode reusable structure; well-built they reduce token-heavy re-derivations."},
  {"q":"''Neo cloud'' GPU providers (e.g., Lambda, Together, Fireworks) typically offer…","type":"single","options":[{"text":"Free GPUs forever","correct":false},{"text":"Cheaper, more flexible GPU/inference vs hyperscalers","correct":true},{"text":"Only training, no inference","correct":false},{"text":"Browser hosting","correct":false}],"explanation":"Specialised GPU clouds compete on price/perf vs AWS/GCP/Azure."},
  {"q":"A common cost trap:","type":"single","options":[{"text":"Tiny prompts","correct":false},{"text":"Huge system prompts attached to every call","correct":true},{"text":"Caching","correct":false},{"text":"Streaming","correct":false}],"explanation":"A 5k-token system prompt × millions of calls = real money."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 24, 'Day 24 — Text2Audio & Text2Video', 70, '[
  {"q":"Which are text-to-video tools? (select all)","type":"multi","options":[{"text":"Veo3","correct":true},{"text":"Higgsfield","correct":true},{"text":"HeyGen","correct":true},{"text":"Excel","correct":false}],"explanation":"All listed are video-gen / avatar-video tools."},
  {"q":"ElevenLabs is best known for…","type":"single","options":[{"text":"Image upscaling","correct":false},{"text":"High-quality voice synthesis and cloning","correct":true},{"text":"Code generation","correct":false},{"text":"Robotics","correct":false}],"explanation":"ElevenLabs leads in TTS and voice cloning."},
  {"q":"A risk of voice cloning is…","type":"single","options":[{"text":"Better latency","correct":false},{"text":"Identity fraud and consent violations","correct":true},{"text":"Higher fidelity always","correct":false},{"text":"Cheaper compute","correct":false}],"explanation":"Cloning without consent enables scams; platforms enforce consent checks."},
  {"q":"For long-form video, generation is usually…","type":"single","options":[{"text":"One-shot end-to-end","correct":false},{"text":"Stitched from short clips with continuity tricks","correct":true},{"text":"Faster than rendering","correct":false},{"text":"Free","correct":false}],"explanation":"Models are length-limited; pipelines compose multiple clips with consistency hacks."},
  {"q":"Provenance tools (e.g., C2PA) help by…","type":"single","options":[{"text":"Compressing files","correct":false},{"text":"Recording how a media asset was created and edited","correct":true},{"text":"Generating new content","correct":false},{"text":"Encrypting voices","correct":false}],"explanation":"Content credentials make AI-generated media traceable to fight deepfakes."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 25, 'Day 25 — Local LLMs, Evals & Tracing', 70, '[
  {"q":"Ollama is primarily used to…","type":"single","options":[{"text":"Train new models","correct":false},{"text":"Run open-weight models locally","correct":true},{"text":"Edit videos","correct":false},{"text":"Replace Git","correct":false}],"explanation":"Ollama makes local inference of open-weight LLMs simple."},
  {"q":"Which are tracing/eval tools? (select all)","type":"multi","options":[{"text":"LangSmith","correct":true},{"text":"Galileo","correct":true},{"text":"OpenEvals","correct":true},{"text":"Photoshop","correct":false}],"explanation":"All listed help observe and evaluate LLM apps."},
  {"q":"A good eval set should…","type":"single","options":[{"text":"Be huge above all","correct":false},{"text":"Cover real, representative tasks with clear pass/fail","correct":true},{"text":"Only test happy paths","correct":false},{"text":"Be secret","correct":false}],"explanation":"Realistic, edge-case-aware, automatable: that''s what moves the model needle."},
  {"q":"Why trace LLM calls?","type":"single","options":[{"text":"Required by law","correct":false},{"text":"To debug, audit, and improve quality","correct":true},{"text":"To save tokens magically","correct":false},{"text":"To slow things down","correct":false}],"explanation":"Tracing reveals what happened in each call/agent step — essential for iteration."},
  {"q":"When does running a local LLM make sense?","type":"single","options":[{"text":"For top SOTA accuracy","correct":false},{"text":"For privacy, cost, offline, or experimentation","correct":true},{"text":"To outsource compute","correct":false},{"text":"Never","correct":false}],"explanation":"Local models trade some quality for control, cost, and privacy."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 26, 'Day 26 — Capstone M5: Agents & Chatbot', 70, '[
  {"q":"A chatbot adds value when it…","type":"single","options":[{"text":"Replicates your existing UI","correct":false},{"text":"Compresses many steps into a conversational shortcut","correct":true},{"text":"Looks cool","correct":false},{"text":"Replaces all forms","correct":false}],"explanation":"Chat is great for fuzzy, multi-step intents that forms handle poorly."},
  {"q":"Good agentic additions to a capstone: (select all)","type":"multi","options":[{"text":"Tool calls to your own DB/API","correct":true},{"text":"A retrieval step over your docs","correct":true},{"text":"Random API calls for show","correct":false},{"text":"Persistent memory of the user''s goal","correct":true}],"explanation":"Tools, retrieval, memory — anchored to real product value."},
  {"q":"Guardrails for an agent include…","type":"single","options":[{"text":"Letting it run forever","correct":false},{"text":"Step caps, allow-listed tools, and confirmations on writes","correct":true},{"text":"Disabling logs","correct":false},{"text":"Sharing system prompts publicly","correct":false}],"explanation":"Bound the agent''s blast radius and you can debug what it actually did."},
  {"q":"M5 must-haves:","type":"single","options":[{"text":"Slick branding only","correct":false},{"text":"At least one agentic flow that demonstrably works","correct":true},{"text":"100% test coverage","correct":false},{"text":"Mobile parity","correct":false}],"explanation":"Show one real agentic flow end-to-end before broadening."},
  {"q":"For chatbot UX, the best default is…","type":"single","options":[{"text":"Hide capabilities and let users guess","correct":false},{"text":"Suggest example prompts and clarify intent","correct":true},{"text":"Long onboarding flows","correct":false},{"text":"No empty state","correct":false}],"explanation":"Suggested prompts dramatically improve task success and discovery."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 27, 'Day 27 — AI Ethics, Safety, Guardrails', 70, '[
  {"q":"Red-teaming an AI system means…","type":"single","options":[{"text":"Branding it red","correct":false},{"text":"Adversarially testing it for failures and misuse","correct":true},{"text":"Auditing finances","correct":false},{"text":"Adding more tools","correct":false}],"explanation":"Red teams probe with hostile inputs to surface harms before users do."},
  {"q":"Which are valid AI guardrails? (select all)","type":"multi","options":[{"text":"Input filtering","correct":true},{"text":"Output classifiers","correct":true},{"text":"Tool allow-lists","correct":true},{"text":"Disabling logs","correct":false}],"explanation":"Layered defences in/out/at-tool-call; logs are essential, not a guardrail to remove."},
  {"q":"Bias in AI usually originates in…","type":"single","options":[{"text":"The colour theme","correct":false},{"text":"Training data and human labelling choices","correct":true},{"text":"The number of GPUs","correct":false},{"text":"User browsers","correct":false}],"explanation":"Models inherit the distributions and labelling biases of their training data."},
  {"q":"A good safety habit before launching:","type":"single","options":[{"text":"Skip review","correct":false},{"text":"Run an internal red-team and document mitigations","correct":true},{"text":"Hide your prompts","correct":false},{"text":"Disable rate limits","correct":false}],"explanation":"Document what you tested and how you mitigated; reviewable trail beats vibes."},
  {"q":"Privacy-preserving design includes…","type":"single","options":[{"text":"Logging full PII forever","correct":false},{"text":"Minimising data collected and retaining only what''s needed","correct":true},{"text":"Sharing with all vendors","correct":false},{"text":"Disabling consent","correct":false}],"explanation":"Data minimisation and purpose-limitation reduce blast radius of any breach."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 28, 'Day 28 — GEO, Benchmarks & Keeping Up', 70, '[
  {"q":"GEO (Generative Engine Optimization) is to LLMs as ___ is to search engines.","type":"single","options":[{"text":"DNS","correct":false},{"text":"SEO","correct":true},{"text":"CDN","correct":false},{"text":"CSS","correct":false}],"explanation":"GEO = optimising your content to be cited/used well by generative engines."},
  {"q":"Why are leaderboards alone an imperfect signal? (select all)","type":"multi","options":[{"text":"They can be gamed / overfit","correct":true},{"text":"They may not reflect your task","correct":true},{"text":"They include all real-world quirks","correct":false},{"text":"They change rapidly","correct":true}],"explanation":"Use leaderboards as a starting filter; validate with your own evals."},
  {"q":"A practical habit for keeping up:","type":"single","options":[{"text":"Read every paper","correct":false},{"text":"Curate a small set of high-signal sources and test things hands-on","correct":true},{"text":"Ignore everything","correct":false},{"text":"Only watch reels","correct":false}],"explanation":"Signal > volume. A small reading list plus hands-on trials beats firehose scrolling."},
  {"q":"When evaluating a new model claim, you should…","type":"single","options":[{"text":"Trust the press release","correct":false},{"text":"Reproduce on your own task with your own evals","correct":true},{"text":"Check Twitter likes","correct":false},{"text":"Ask the vendor only","correct":false}],"explanation":"Public claims rarely match your task distribution; your eval is the truth."},
  {"q":"Benchmarks ideally are…","type":"single","options":[{"text":"Static and old","correct":false},{"text":"Refreshed, contamination-aware, and task-relevant","correct":true},{"text":"Secret","correct":false},{"text":"Single-metric","correct":false}],"explanation":"Models can memorise public benchmarks; rotating + relevant evals stay honest."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 29, 'Day 29 — Demo Day 1', 70, '[
  {"q":"On Demo Day, the most important thing is…","type":"single","options":[{"text":"Show every feature","correct":false},{"text":"Tell a clear story end-to-end","correct":true},{"text":"Use the latest model","correct":false},{"text":"Wear matching shirts","correct":false}],"explanation":"Audiences remember stories, not feature lists."},
  {"q":"Demo-readiness checklist: (select all)","type":"multi","options":[{"text":"Backup video recorded","correct":true},{"text":"Stable demo data prepared","correct":true},{"text":"Network and login tested","correct":true},{"text":"Live coding from scratch","correct":false}],"explanation":"Reduce live failure modes; never code from scratch in a demo."},
  {"q":"A great pitch ends with…","type":"single","options":[{"text":"A vague ''thanks''","correct":false},{"text":"A specific ask","correct":true},{"text":"More slides","correct":false},{"text":"Q&A only","correct":false}],"explanation":"Tell the audience exactly what you want next (users, intros, feedback)."},
  {"q":"If something breaks live, the best move is…","type":"single","options":[{"text":"Panic","correct":false},{"text":"Switch calmly to backup and keep the story moving","correct":true},{"text":"Restart the laptop","correct":false},{"text":"Blame Wi-Fi","correct":false}],"explanation":"Composure + a backup makes a stumble forgettable."},
  {"q":"After your demo, you should…","type":"single","options":[{"text":"Hide","correct":false},{"text":"Capture feedback and follow up with interested folks","correct":true},{"text":"Delete the repo","correct":false},{"text":"Stop iterating","correct":false}],"explanation":"The demo is the start of conversations, not the end."}
]'::jsonb),
('56268633-9e93-4305-af6a-1b622a833d8e', 30, 'Day 30 — Demo Day 2 & Beyond', 70, '[
  {"q":"Post-workshop, the highest-leverage habit is…","type":"single","options":[{"text":"Stop coding","correct":false},{"text":"Ship small things consistently","correct":true},{"text":"Wait for the next course","correct":false},{"text":"Only read papers","correct":false}],"explanation":"Compounding tiny shipped projects beats ''one big project some day''."},
  {"q":"Strong portfolio artifacts: (select all)","type":"multi","options":[{"text":"Live deployed app","correct":true},{"text":"Public GitHub with a clear README","correct":true},{"text":"Short demo video","correct":true},{"text":"Long PDF nobody reads","correct":false}],"explanation":"Make it one click for someone to see your work."},
  {"q":"Best way to keep AI skills sharp:","type":"single","options":[{"text":"Memorise model names","correct":false},{"text":"Build small projects and write up what you learned","correct":true},{"text":"Only watch videos","correct":false},{"text":"Avoid documentation","correct":false}],"explanation":"Build + reflect creates durable skill; passive consumption fades fast."},
  {"q":"A healthy view of AI tools:","type":"single","options":[{"text":"Replace your judgement","correct":false},{"text":"Augment your judgement, with verification","correct":true},{"text":"Always trust them","correct":false},{"text":"Never use them","correct":false}],"explanation":"Treat models as fast, fallible collaborators — not oracles."},
  {"q":"The best long-term moat as an AI builder is…","type":"single","options":[{"text":"Knowing one tool","correct":false},{"text":"Taste, judgement, and shipping discipline","correct":true},{"text":"Hoarding API keys","correct":false},{"text":"Following hype","correct":false}],"explanation":"Tools change monthly; taste and execution compound for years."}
]'::jsonb);

-- 3. Reseed polls
insert into public.polls (cohort_id, day_number, title, question, kind, options, is_open) values
('56268633-9e93-4305-af6a-1b622a833d8e', 1, 'Day 1 Pulse', 'How would you rate your current comfort level with AI?', 'single', to_jsonb(array['Beginner — barely used it','Casual user — chat now and then','Confident — daily user','Power user — building with it']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 2, 'Day 2 Pulse', 'Which LLM concept feels most confusing right now?', 'single', to_jsonb(array['Tokens','Attention','Weights','Memory / context']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 3, 'Day 3 Pulse', 'Which prompting technique do you reach for most?', 'single', to_jsonb(array['Plain instructions','Few-shot examples','Chain-of-thought','Structured output']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 4, 'Day 4 Pulse', 'Have you ever run an open-source model yourself?', 'single', to_jsonb(array['Never','Tried once','A few times','Regularly']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 5, 'Day 5 Pulse', 'Which research mode do you trust the most?', 'single', to_jsonb(array['Fast / quick answer','Thinking mode','Deep research with sources','I verify everything manually']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 6, 'Day 6 Pulse', 'How clear is your capstone problem statement right now?', 'single', to_jsonb(array['No idea yet','Vague direction','Decent draft','Crisp and validated']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 7, 'Day 7 Pulse', 'Which framing tool felt most useful today?', 'single', to_jsonb(array['Heilmeier Catechism','5 Whys','How Might We','Still figuring it out']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 8, 'Day 8 Pulse', 'Which stage of design thinking feels hardest for you?', 'single', to_jsonb(array['Empathize','Define','Ideate','Prototype / Test']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 9, 'Day 9 Pulse', 'How many real users have you talked to about your idea?', 'single', to_jsonb(array['Zero','1–2','3–5','6 or more']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 10, 'Day 10 Pulse', 'Which systems-thinking tool will you actually use this week?', 'single', to_jsonb(array['Causal loop diagram','Leverage points','SCQA','Mind map']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 11, 'Day 11 Pulse', 'How locked is your capstone idea after M2?', 'single', to_jsonb(array['Still wobbling','Mostly there','Locked','Locked and validated']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 12, 'Day 12 Pulse', 'Which image tool will you use for your capstone?', 'single', to_jsonb(array['Stable Diffusion','ChatGPT Images','Nano Banana','Adobe Firefly']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 13, 'Day 13 Pulse', 'What''s the first workflow you want to automate?', 'single', to_jsonb(array['Email / inbox triage','Scraping / research','Reporting / digests','Onboarding / forms']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 14, 'Day 14 Pulse', 'Which AI deck tool felt best?', 'single', to_jsonb(array['Gamma','Kimi','Canva','None — I''ll do it by hand']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 15, 'Day 15 Pulse', 'How comfortable are you ''vibe coding'' a small feature?', 'single', to_jsonb(array['Not at all','Need help','Comfortable','Already doing it']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 16, 'Day 16 Pulse', 'How did your M3 mini demo go?', 'single', to_jsonb(array['Crashed','Worked partially','Worked end-to-end','Beyond expectations']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 17, 'Day 17 Pulse', 'Where''s your Git comfort level?', 'single', to_jsonb(array['Never used','Add/commit/push','Branches and merges','Rebases and recovery']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 18, 'Day 18 Pulse', 'Have you deployed anything before today?', 'single', to_jsonb(array['Never','Once','A few projects','Many']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 19, 'Day 19 Pulse', 'For your capstone, which fits best?', 'single', to_jsonb(array['Plain prompts','Prompts + few-shot','RAG with embeddings','Fine-tuning']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 20, 'Day 20 Pulse', 'Will you maintain a CLAUDE.md / AGENTS.md for your capstone?', 'single', to_jsonb(array['Yes — already started','Yes — will start today','Maybe','No']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 21, 'Day 21 Pulse', 'How''s your first deploy looking?', 'single', to_jsonb(array['Not deployed yet','Deployed but broken','Deployed and shaky','Deployed and stable']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 22, 'Day 22 Pulse', 'Which agentic pattern excites you most?', 'single', to_jsonb(array['Single agent + tools','ReAct loops','Multi-agent collaboration','MCP-connected agents']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 23, 'Day 23 Pulse', 'How well do you understand your project''s LLM cost structure?', 'single', to_jsonb(array['Not at all','Rough idea','Good model','Tracked per request']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 24, 'Day 24 Pulse', 'Which generative media is most relevant to your capstone?', 'single', to_jsonb(array['Audio / voice','Avatars / talking heads','Short-form video','Not relevant']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 25, 'Day 25 Pulse', 'Will you run a local LLM during the workshop?', 'single', to_jsonb(array['No','Maybe','Yes — for privacy','Yes — for experimentation']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 26, 'Day 26 Pulse', 'How does your capstone agent / chatbot feel?', 'single', to_jsonb(array['Not started','Prototype only','Works on happy path','Robust enough to demo']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 27, 'Day 27 Pulse', 'Which AI risk worries you most for your capstone?', 'single', to_jsonb(array['Bias / unfair outputs','Privacy leakage','Hallucinations','Misuse / abuse']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 28, 'Day 28 Pulse', 'How will you keep up with AI after the workshop?', 'single', to_jsonb(array['Newsletters','Hands-on building','Papers / podcasts','Community / Slack']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 29, 'Day 29 Pulse', 'How ready do you feel for Demo Day?', 'single', to_jsonb(array['Not ready','Getting there','Ready','Ready and rehearsed']), false),
('56268633-9e93-4305-af6a-1b622a833d8e', 30, 'Day 30 Pulse', 'What''s your next move after the workshop?', 'single', to_jsonb(array['Keep iterating capstone','Start a new project','Job / internship hunt','Teach others']), false);

-- 4. Reseed assignments
insert into public.assignments (cohort_id, day_number, title, points, rubric_items, due_at) values
('56268633-9e93-4305-af6a-1b622a833d8e', 1, 'Map your AI today', 10, '[
  {"id":"1","name":"Coverage","description":"Lists at least 5 AI touchpoints in your daily life across categories.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"5+ varied, specific examples"},{"score":2,"label":"Partial","description":"3–4 examples, some vague"},{"score":0,"label":"Missing","description":"Fewer than 3 or all vague"}]},
  {"id":"2","name":"Insight","description":"Names where AI helps vs where it can mislead.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Clear pros and risks per item"},{"score":1,"label":"Partial","description":"Generic pros/cons"},{"score":0,"label":"Missing","description":"No reflection"}]},
  {"id":"3","name":"Clarity","description":"Submission is concise and well-structured.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Tight, scannable, no fluff"},{"score":1,"label":"Partial","description":"Readable but rambly"},{"score":0,"label":"Missing","description":"Hard to follow"}]}
]'::jsonb, '2026-05-02 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 2, 'Tokenize and explain', 10, '[
  {"id":"1","name":"Demonstration","description":"Tokenizes a sample paragraph and shows the token boundaries.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"Clear, accurate tokenization shown"},{"score":2,"label":"Partial","description":"Tokenized but unclear"},{"score":0,"label":"Missing","description":"No tokenization"}]},
  {"id":"2","name":"Explanation","description":"Explains attention, weights, and context window in your own words.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"All three correct and clear"},{"score":2,"label":"Partial","description":"1–2 explained well"},{"score":0,"label":"Missing","description":"Copy-paste / wrong"}]},
  {"id":"3","name":"Application","description":"Connects concepts to a real-world LLM behaviour you''ve seen.","max_points":2,"levels":[{"score":2,"label":"Strong","description":"Specific, illustrative example"},{"score":1,"label":"Partial","description":"Generic example"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-05-05 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 3, 'CREATE prompt rewrite', 10, '[
  {"id":"1","name":"Before/After","description":"Shows a weak prompt and a CREATE-structured rewrite.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"Clear improvement, all 6 elements present"},{"score":2,"label":"Partial","description":"Some elements missing"},{"score":0,"label":"Missing","description":"No rewrite"}]},
  {"id":"2","name":"Output quality","description":"Compares model outputs from both prompts.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Side-by-side with analysis"},{"score":1,"label":"Partial","description":"Outputs without analysis"},{"score":0,"label":"Missing","description":"No comparison"}]},
  {"id":"3","name":"Reflection","description":"Notes what changed and why.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Specific, actionable insight"},{"score":1,"label":"Partial","description":"Vague reflection"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-05-06 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 4, 'Open model bake-off', 10, '[
  {"id":"1","name":"Coverage","description":"Tests the same prompt on at least 3 open-source models.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"3+ models, varied families"},{"score":2,"label":"Partial","description":"2 models"},{"score":0,"label":"Missing","description":"1 or none"}]},
  {"id":"2","name":"Comparison","description":"Notes accuracy, tone, and Indic-language handling where relevant.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Concrete, specific differences"},{"score":1,"label":"Partial","description":"Generic notes"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"3","name":"Recommendation","description":"Picks one for a stated use case and justifies.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Justified with evidence"},{"score":1,"label":"Partial","description":"Pick without strong reason"},{"score":0,"label":"Missing","description":"No pick"}]}
]'::jsonb, '2026-05-07 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 5, 'Grounded research mini-report', 10, '[
  {"id":"1","name":"Sourcing","description":"At least 3 distinct, credible sources cited.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"3+ varied, credible, recent"},{"score":2,"label":"Partial","description":"2 sources or low credibility"},{"score":0,"label":"Missing","description":"Few/no sources"}]},
  {"id":"2","name":"Synthesis","description":"Goes beyond summary to compare and conclude.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Real synthesis"},{"score":1,"label":"Partial","description":"Mostly summary"},{"score":0,"label":"Missing","description":"Quotes only"}]},
  {"id":"3","name":"Verification","description":"Notes one citation you spot-checked yourself.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Clear verification trail"},{"score":1,"label":"Partial","description":"Mentioned vaguely"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-05-08 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 6, 'Capstone M1 — Idea one-pager', 25, '[
  {"id":"1","name":"Problem & user","description":"Names a specific user and pain with evidence.","max_points":10,"levels":[{"score":10,"label":"Strong","description":"Specific user, vivid pain, evidence"},{"score":6,"label":"Partial","description":"Generic user or pain"},{"score":0,"label":"Missing","description":"No user defined"}]},
  {"id":"2","name":"Why now / why AI","description":"Explains why this is solvable now and where AI helps.","max_points":8,"levels":[{"score":8,"label":"Strong","description":"Clear rationale"},{"score":4,"label":"Partial","description":"Hand-wavy"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"3","name":"Validation plan","description":"Names how you''ll talk to users this week.","max_points":7,"levels":[{"score":7,"label":"Strong","description":"Concrete plan and targets"},{"score":3,"label":"Partial","description":"Vague plan"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-05-09 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 7, 'Heilmeier-ize your project', 10, '[
  {"id":"1","name":"Plain language","description":"Answers the first Heilmeier question with no jargon.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"Crystal clear to a non-expert"},{"score":2,"label":"Partial","description":"Some jargon"},{"score":0,"label":"Missing","description":"Unreadable"}]},
  {"id":"2","name":"Risks & mitigations","description":"Lists honest risks and concrete mitigations.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Specific risks + mitigations"},{"score":1,"label":"Partial","description":"Generic"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"3","name":"Success criteria","description":"Defines how you''ll know it''s working.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Measurable criteria"},{"score":1,"label":"Partial","description":"Soft criteria"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-05-12 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 8, 'Empathize → Define for your capstone', 10, '[
  {"id":"1","name":"Empathy data","description":"Captures real user observations or quotes.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"Specific, vivid quotes/notes"},{"score":2,"label":"Partial","description":"Generic notes"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"2","name":"POV statement","description":"Synthesises into a sharp point-of-view.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Crisp POV with insight"},{"score":1,"label":"Partial","description":"Vague POV"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"3","name":"HMW questions","description":"Generates 3+ ''How Might We'' framings.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"3+ varied HMWs"},{"score":1,"label":"Partial","description":"1–2 HMWs"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-05-13 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 9, 'Three Mom-Test interviews', 10, '[
  {"id":"1","name":"Conduct","description":"Completes 3 user interviews using behaviour-focused questions.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"3 interviews, good questions"},{"score":2,"label":"Partial","description":"1–2 interviews"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"2","name":"Notes","description":"Captures specific stories, not opinions.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Behavioural detail"},{"score":1,"label":"Partial","description":"Mostly opinions"},{"score":0,"label":"Missing","description":"No notes"}]},
  {"id":"3","name":"Insight","description":"Names 2+ surprises and what changes for your idea.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Real shifts identified"},{"score":1,"label":"Partial","description":"Surface insight"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-05-14 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 10, 'Causal loop diagram for your problem', 10, '[
  {"id":"1","name":"Variables","description":"Identifies 6+ relevant variables and their direction of influence.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"Complete, accurate map"},{"score":2,"label":"Partial","description":"Sparse or unclear"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"2","name":"Loops","description":"Identifies at least one R and one B loop.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Both loops named correctly"},{"score":1,"label":"Partial","description":"One identified"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"3","name":"Leverage","description":"Names a high-leverage intervention point and rationale.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Specific, justified"},{"score":1,"label":"Partial","description":"Vague"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-05-15 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 11, 'Capstone M2 — Idea Lock & feature cut', 25, '[
  {"id":"1","name":"Locked statement","description":"Crisp problem-user-value statement with no waffle.","max_points":10,"levels":[{"score":10,"label":"Strong","description":"Sharp, specific, evidence-backed"},{"score":6,"label":"Partial","description":"Mostly there"},{"score":0,"label":"Missing","description":"Vague"}]},
  {"id":"2","name":"v1 feature cut","description":"Lists v1 features with explicit ''later'' parking lot.","max_points":8,"levels":[{"score":8,"label":"Strong","description":"Clear cut, defensible scope"},{"score":4,"label":"Partial","description":"Long unprioritised list"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"3","name":"AI role","description":"Names exactly where AI adds value vs deterministic logic.","max_points":7,"levels":[{"score":7,"label":"Strong","description":"Clear AI/non-AI split"},{"score":3,"label":"Partial","description":"Partial reasoning"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-05-16 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 12, 'Hero image generation', 10, '[
  {"id":"1","name":"Iteration","description":"Shows at least 4 iterations toward a chosen image.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"4+ varied iterations"},{"score":2,"label":"Partial","description":"2–3 iterations"},{"score":0,"label":"Missing","description":"One-shot only"}]},
  {"id":"2","name":"Prompt craft","description":"Demonstrates use of negative prompts, seeds, or aspect tweaks.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Multiple craft techniques"},{"score":1,"label":"Partial","description":"One technique"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"3","name":"Fit","description":"Final image fits the capstone brand/use case.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"On-brand and useful"},{"score":1,"label":"Partial","description":"Decoration only"},{"score":0,"label":"Missing","description":"Off-brand"}]}
]'::jsonb, '2026-05-19 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 13, 'Build one automation workflow', 10, '[
  {"id":"1","name":"Workflow","description":"Working n8n/Zapier flow that triggers and runs end-to-end.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"Reliable, end-to-end"},{"score":2,"label":"Partial","description":"Runs sometimes"},{"score":0,"label":"Missing","description":"Doesn''t run"}]},
  {"id":"2","name":"Value","description":"Automates a real, repetitive task.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Genuine time-saver"},{"score":1,"label":"Partial","description":"Toy demo"},{"score":0,"label":"Missing","description":"No value"}]},
  {"id":"3","name":"Robustness","description":"Handles at least one failure mode (retry/alert/log).","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Failure path tested"},{"score":1,"label":"Partial","description":"Mentioned only"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-05-20 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 14, 'AI-generated 6-slide deck', 10, '[
  {"id":"1","name":"Narrative","description":"Slides tell a coherent problem→solution→ask story.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"Tight, compelling story"},{"score":2,"label":"Partial","description":"Loose narrative"},{"score":0,"label":"Missing","description":"Disjointed"}]},
  {"id":"2","name":"Design","description":"Clean, one-idea-per-slide, readable.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Polished and scannable"},{"score":1,"label":"Partial","description":"Crowded slides"},{"score":0,"label":"Missing","description":"Hard to read"}]},
  {"id":"3","name":"Edit","description":"Shows what you edited from the AI''s draft and why.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Clear human-in-the-loop edits"},{"score":1,"label":"Partial","description":"Light edits"},{"score":0,"label":"Missing","description":"Untouched output"}]}
]'::jsonb, '2026-05-21 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 15, 'Vibe-code one capstone feature', 10, '[
  {"id":"1","name":"Feature works","description":"A real feature in your capstone, end-to-end, runs.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"Works reliably"},{"score":2,"label":"Partial","description":"Works on happy path"},{"score":0,"label":"Missing","description":"Doesn''t run"}]},
  {"id":"2","name":"AI collaboration","description":"Shows how you steered the AI (plans, diffs, rejections).","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Clear steering trail"},{"score":1,"label":"Partial","description":"Some evidence"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"3","name":"Understanding","description":"Can explain every line of generated code you accepted.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Full understanding"},{"score":1,"label":"Partial","description":"Most of it"},{"score":0,"label":"Missing","description":"Black box"}]}
]'::jsonb, '2026-05-22 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 16, 'Capstone M3 — Mini demo & pitch', 25, '[
  {"id":"1","name":"Working demo","description":"At least one end-to-end flow runs live.","max_points":10,"levels":[{"score":10,"label":"Strong","description":"Reliable, end-to-end"},{"score":6,"label":"Partial","description":"Mostly works"},{"score":0,"label":"Missing","description":"Doesn''t run"}]},
  {"id":"2","name":"Pitch","description":"3-min pitch with pain → solution → ask.","max_points":8,"levels":[{"score":8,"label":"Strong","description":"Clear, well-paced"},{"score":4,"label":"Partial","description":"Rambly or missing pieces"},{"score":0,"label":"Missing","description":"No pitch"}]},
  {"id":"3","name":"Reflection","description":"Names what to change before M4 based on feedback.","max_points":7,"levels":[{"score":7,"label":"Strong","description":"Specific next steps"},{"score":3,"label":"Partial","description":"Generic"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-05-23 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 17, 'Push your capstone to GitHub', 10, '[
  {"id":"1","name":"Repo hygiene","description":"README, .gitignore, no secrets, clean history.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"All in place"},{"score":2,"label":"Partial","description":"Some missing"},{"score":0,"label":"Missing","description":"Sloppy or unsafe"}]},
  {"id":"2","name":"API call","description":"Code that calls a real API with proper key handling.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Working call, env-var keys"},{"score":1,"label":"Partial","description":"Hardcoded keys"},{"score":0,"label":"Missing","description":"No API call"}]},
  {"id":"3","name":"Local run","description":"Anyone can clone and run with the README.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Reproducible"},{"score":1,"label":"Partial","description":"Some friction"},{"score":0,"label":"Missing","description":"Broken locally"}]}
]'::jsonb, '2026-05-26 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 18, 'Ship a Vercel + Supabase deploy', 10, '[
  {"id":"1","name":"Live URL","description":"Public URL serves your app.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"Live and stable"},{"score":2,"label":"Partial","description":"Live but flaky"},{"score":0,"label":"Missing","description":"Not deployed"}]},
  {"id":"2","name":"Auth + DB","description":"Supabase auth + at least one table working.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Both work"},{"score":1,"label":"Partial","description":"One works"},{"score":0,"label":"Missing","description":"Neither"}]},
  {"id":"3","name":"RLS","description":"Row-level security policies in place for user data.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Policies tested"},{"score":1,"label":"Partial","description":"Defaults only"},{"score":0,"label":"Missing","description":"Wide open"}]}
]'::jsonb, '2026-05-27 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 19, 'Build a tiny RAG demo', 10, '[
  {"id":"1","name":"Pipeline","description":"Chunks → embeds → indexes → retrieves → prompts.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"All stages working"},{"score":2,"label":"Partial","description":"Stages skipped"},{"score":0,"label":"Missing","description":"Doesn''t run"}]},
  {"id":"2","name":"Quality","description":"Answers cite the right chunks for sample questions.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Accurate citations"},{"score":1,"label":"Partial","description":"Sometimes wrong"},{"score":0,"label":"Missing","description":"No citations"}]},
  {"id":"3","name":"Reflection","description":"Notes failure modes and chunking trade-offs.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Specific insight"},{"score":1,"label":"Partial","description":"Surface notes"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-05-28 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 20, 'Author your capstone CLAUDE.md', 10, '[
  {"id":"1","name":"Architecture notes","description":"Captures non-obvious project quirks.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"High-signal, specific"},{"score":2,"label":"Partial","description":"Generic boilerplate"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"2","name":"Conventions","description":"Documents naming, migrations, testing conventions.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Clear and useful"},{"score":1,"label":"Partial","description":"Sparse"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"3","name":"Skills/Rules","description":"Adds at least one project Skill or Rule that''s actually useful.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Demonstrably useful"},{"score":1,"label":"Partial","description":"Token effort"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-05-29 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 21, 'Capstone M4 — Workspace & first deploy', 25, '[
  {"id":"1","name":"Repo & deploy","description":"Clean repo + live deploy with env vars set.","max_points":10,"levels":[{"score":10,"label":"Strong","description":"Both production-quality"},{"score":6,"label":"Partial","description":"One rough"},{"score":0,"label":"Missing","description":"Broken or absent"}]},
  {"id":"2","name":"Auth & data","description":"Auth flow + persisted user data work.","max_points":8,"levels":[{"score":8,"label":"Strong","description":"End-to-end works"},{"score":4,"label":"Partial","description":"Partial"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"3","name":"Docs","description":"README explains setup, env, and how to run/deploy.","max_points":7,"levels":[{"score":7,"label":"Strong","description":"Friendly and complete"},{"score":3,"label":"Partial","description":"Sketchy"},{"score":0,"label":"Missing","description":"Absent"}]}
]'::jsonb, '2026-05-30 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 22, 'Add an agent with a tool call', 10, '[
  {"id":"1","name":"Agent loop","description":"Agent reasons and calls a tool to complete a task.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"Reliable ReAct loop"},{"score":2,"label":"Partial","description":"Loops or errors"},{"score":0,"label":"Missing","description":"Single-shot only"}]},
  {"id":"2","name":"Tool design","description":"At least one tool with clear schema and validation.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Typed and validated"},{"score":1,"label":"Partial","description":"Loose schema"},{"score":0,"label":"Missing","description":"No schema"}]},
  {"id":"3","name":"Guardrails","description":"Step cap + tool allow-list in place.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Both implemented"},{"score":1,"label":"Partial","description":"One only"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-06-02 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 23, 'Cost model your capstone', 10, '[
  {"id":"1","name":"Per-request cost","description":"Estimates input/output tokens and $ per request.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"Realistic numbers"},{"score":2,"label":"Partial","description":"Rough guess"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"2","name":"Monthly projection","description":"Projects cost at expected user volume.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Defensible projection"},{"score":1,"label":"Partial","description":"Hand-wavy"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"3","name":"Optimisations","description":"Lists at least 3 specific cost levers (cache, smaller model, prompt trim).","max_points":3,"levels":[{"score":3,"label":"Strong","description":"3+ concrete levers"},{"score":1,"label":"Partial","description":"1–2"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-06-03 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 24, 'Generate a 30-second product video', 10, '[
  {"id":"1","name":"Output","description":"Final video runs end-to-end and shows your concept.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"Clean, on-message"},{"score":2,"label":"Partial","description":"Rough cuts"},{"score":0,"label":"Missing","description":"No video"}]},
  {"id":"2","name":"Pipeline","description":"Combines at least 2 tools (TTS + video, avatar + edits, etc.).","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Multiple tools used"},{"score":1,"label":"Partial","description":"One tool"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"3","name":"Provenance","description":"Notes which assets are AI-generated and consent considerations.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Clear disclosure"},{"score":1,"label":"Partial","description":"Mentioned"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-06-04 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 25, 'Run a small eval set', 10, '[
  {"id":"1","name":"Eval set","description":"At least 10 test cases for a specific behaviour.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"Varied, realistic cases"},{"score":2,"label":"Partial","description":"Few or trivial"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"2","name":"Tracing","description":"Calls instrumented in LangSmith / OpenEvals / similar.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Traces visible"},{"score":1,"label":"Partial","description":"Partial setup"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"3","name":"Findings","description":"Names at least 2 concrete improvements from the data.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Specific, actionable"},{"score":1,"label":"Partial","description":"Vague"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-06-05 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 26, 'Capstone M5 — Agent + chatbot integrated', 25, '[
  {"id":"1","name":"Integrated agent","description":"Agent or chatbot is part of the deployed app, not a side script.","max_points":10,"levels":[{"score":10,"label":"Strong","description":"Wired into product"},{"score":6,"label":"Partial","description":"Mostly wired"},{"score":0,"label":"Missing","description":"Standalone only"}]},
  {"id":"2","name":"Real value","description":"Solves a concrete user task end-to-end.","max_points":8,"levels":[{"score":8,"label":"Strong","description":"Genuine value"},{"score":4,"label":"Partial","description":"Toy task"},{"score":0,"label":"Missing","description":"No clear task"}]},
  {"id":"3","name":"Safety","description":"Step caps, allow-listed tools, error handling visible.","max_points":7,"levels":[{"score":7,"label":"Strong","description":"All present"},{"score":3,"label":"Partial","description":"Some present"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-06-06 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 27, 'Red-team your capstone', 10, '[
  {"id":"1","name":"Attack set","description":"Lists 5+ adversarial inputs you tried.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"Diverse, realistic attacks"},{"score":2,"label":"Partial","description":"Few or trivial"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"2","name":"Findings","description":"Documents what broke or behaved unsafely.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Clear, specific failures"},{"score":1,"label":"Partial","description":"Vague"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"3","name":"Mitigations","description":"Implements or plans at least one mitigation.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Implemented and tested"},{"score":1,"label":"Partial","description":"Planned only"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-06-09 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 28, 'Personal AI learning plan', 10, '[
  {"id":"1","name":"Sources","description":"Curates a tight list of newsletters/podcasts/blogs (≤7).","max_points":4,"levels":[{"score":4,"label":"Strong","description":"High-signal and varied"},{"score":2,"label":"Partial","description":"Generic list"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"2","name":"Cadence","description":"Defines a weekly/monthly review and build cadence.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Realistic and specific"},{"score":1,"label":"Partial","description":"Aspirational"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"3","name":"Eval habit","description":"Names how you''ll test new tools/models on your tasks.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Concrete eval habit"},{"score":1,"label":"Partial","description":"Vague"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-06-10 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 29, 'Demo Day 1 dry run', 10, '[
  {"id":"1","name":"Rehearsal","description":"Records a full dry-run of your demo + pitch.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"On time, clean"},{"score":2,"label":"Partial","description":"Over time / rough"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"2","name":"Backup ready","description":"Backup video + screenshots prepared in case live fails.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Both ready"},{"score":1,"label":"Partial","description":"One ready"},{"score":0,"label":"Missing","description":"Neither"}]},
  {"id":"3","name":"Ask","description":"Pitch ends with a specific, useful ask.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Clear, concrete ask"},{"score":1,"label":"Partial","description":"Generic"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-06-11 21:00+05:30'::timestamptz),
('56268633-9e93-4305-af6a-1b622a833d8e', 30, 'Demo Day 2 — final delivery & retro', 10, '[
  {"id":"1","name":"Final demo","description":"Delivers a polished demo at Demo Day 2.","max_points":4,"levels":[{"score":4,"label":"Strong","description":"Polished and confident"},{"score":2,"label":"Partial","description":"Solid but rough edges"},{"score":0,"label":"Missing","description":"Did not deliver"}]},
  {"id":"2","name":"Retro","description":"Writes a short retro: what worked, what didn''t, what next.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Honest and specific"},{"score":1,"label":"Partial","description":"Surface-level"},{"score":0,"label":"Missing","description":"None"}]},
  {"id":"3","name":"Next steps","description":"Concrete plan for the next 30 days post-workshop.","max_points":3,"levels":[{"score":3,"label":"Strong","description":"Specific milestones"},{"score":1,"label":"Partial","description":"Vague intentions"},{"score":0,"label":"Missing","description":"None"}]}
]'::jsonb, '2026-06-12 21:00+05:30'::timestamptz);

commit;
