---
day: 14
date: "2026-05-20"
weekday: "Wednesday"
week: 3
topic: "Making Presentation with AI"
faculty:
  main: "Sanjana"
  support: "Jayasaagar"
reading_time: "10 min"
tldr: "Stop fighting PowerPoint. Today you turn a one-line idea into a 10-slide deck in under 20 minutes — Gamma for layout, Kimi for the script, Canva for the polish. Bring your capstone idea; leave with a deck."
tags: ["presentation", "design", "tools"]
software: []
online_tools: ["Gamma AI", "Kimi AI", "Canva"]
video: "https://www.youtube.com/embed/KcbXKUR7-a0"
prompt_of_the_day: "Create a 10-slide pitch deck for a college-canteen UPI bill-splitter app aimed at hostel students in Tier-2 Indian colleges. Cover: problem, user, solution, demo flow, why-now, competitors, GTM on campus, ask. Tone: confident, no jargon."
tools_hands_on:
  - { name: "Gamma AI", url: "https://gamma.app/" }
  - { name: "Kimi AI", url: "https://kimi.com/" }
  - { name: "Canva", url: "https://www.canva.com/" }
tools_reference:
  - { name: "Gamma — Generate from prompt", url: "https://gamma.app/create" }
  - { name: "Canva Magic Design", url: "https://www.canva.com/magic-design/" }
resources:
  - { title: "Guy Kawasaki — 10/20/30 rule", url: "https://guykawasaki.com/the_102030_rule/" }
  - { title: "Garr Reynolds — Presentation Zen", url: "https://www.presentationzen.com/" }
lab: { title: "Idea → 10-slide deck in 20 min", url: "https://gamma.app/" }
objective:
  topic: "Making Presentation with AI"
  tools: ["Gamma AI", "Kimi AI", "Canva"]
  end_goal: "A 10-slide deck for your capstone idea, generated with Gamma, scripted with Kimi, polished in Canva."
---

Slides used to be the bottleneck. With Gamma, Kimi, and Canva you can stop polishing pixels and focus on the *story*. Today is a make-the-deck-during-class day — you walk out with something you'd actually present.

## 🎯 Today's objective

**Topic.** Making Presentation with AI.

**By end of class you will have:**
1. A 10-slide draft deck generated by Gamma from a single prompt about your capstone idea.
2. A 60-second spoken script written by Kimi AI for slide 1 (the hook) and slide 10 (the ask).
3. One slide visually upgraded in Canva — fonts, image, brand colour.

> *Why this matters.* Day 16 you pitch your capstone in 5 minutes. The deck you start today is what you'll refine.

## ⏪ Pre-class · ~20 min

### Setup (required)

- [ ] Sign up for **Gamma** (free tier — 400 AI credits), **Kimi AI**, and **Canva** with your college email.
- [ ] One-line capstone idea written down (you'll paste it into Gamma).

### Primer (~5 min)

- **Read:** Guy Kawasaki's 10/20/30 rule — https://guykawasaki.com/the_102030_rule/
- **Watch:** Any 3-min Gamma demo on YouTube to see the generate-from-prompt flow.

### Bring to class

- [ ] One photo (your team, campus, mock UI screenshot) you might use as a hero image.

> 🧠 **Quick glossary.** **Generative deck** = AI builds slide structure + copy + images from a prompt. **Theme** = Gamma's reusable look. **Card** = Gamma's word for slide. **Magic Design** = Canva's prompt-to-design feature.

## 🎥 In-class · live session

### Agenda

| Block | Time | What |
|---|---|---|
| Demo: same idea, three tools | 10 min | Gamma vs Canva vs raw Slides |
| Live build: Gamma deck | 20 min | Prompt → 10 cards → edit two |
| Kimi script-writing | 10 min | Hook + ask in your voice |
| Canva polish | 10 min | One slide, lift it |
| Poll + Q&A | 10 min | Which tool won for which job |

### What AI presentation tools are *for*

1. **Speed of first draft** — 10 slides in 90 seconds, not 90 minutes.
2. **Layout decisions you'd otherwise stall on** — title size, image placement, hierarchy.
3. **Tone-matched copy** — pitch, training, classroom — all from the same outline.

### What they're *not* for

1. **Doing your thinking** — a generated deck is only as good as the idea you fed it.
2. **Final-mile polish** — export to Canva or Slides for the last 10% of design love.
3. **Presenting *for* you** — the deck doesn't replace rehearsal.

## 🧪 Lab: Idea → 10-slide deck

1. Open **Gamma** → *Generate* → paste the prompt of the day (swap in your own capstone idea).
2. Pick a theme. Let it generate. Skim all 10 cards in 60 seconds.
3. Edit **two cards**: rewrite the headline on slide 1, replace one stock image on slide 5.
4. Open **Kimi AI**. Prompt: *"Write a 60-second spoken script for slide 1 of this deck — hook me on the problem in 3 sentences."* Paste your slide 1 copy as context. Repeat for slide 10 (the ask).
5. Open **Canva** → import slide 1 as PNG → run *Magic Design* with the same prompt → keep whichever version reads better.
6. Export the Gamma deck as PDF.

**Artifact.** PDF of the 10-slide deck + a Google Doc with your two scripts. Drop both links in the cohort channel.

## 📊 Live poll

**Which tool would you reach for first for a *campus club* pitch?** Gamma / Canva / Kimi-then-Slides / Plain Google Slides / Depends on audience.

## 💬 Discuss

- Where did Gamma's auto-generated copy nail your idea, and where did it sound generic?
- Pitching to a Tier-2 college fest committee vs a YC partner — which tool changes, and why?
- Name one slide in your generated deck that you'd delete entirely. What's missing instead?

## ❓ Quiz

Short quiz on Gamma cards vs Canva pages, when to use Magic Design, and the 10/20/30 rule. Open it on your dashboard.

## 📝 Assignment · Capstone deck v1

**Brief.** Polish your 10-slide deck into a v1 you'd actually show. Add real numbers (your campus, your users) on at least 2 slides. Replace at least one stock image with a real screenshot or photo.

**Submit.** Share the Gamma link (set to *anyone with link*) on the dashboard.

**Rubric.** Story arc (4) · Concrete numbers/visuals (4) · Visual consistency (2).

## 🔁 Prep for next class

Day 15 is **Vibe Coding** — you'll build an actual app from a prompt using Antigravity, Cursor, Bolt, Emergent.

- [ ] Install **Antigravity** (https://antigravity.google/) — primary editor for Vibe Coding. **Cursor** (https://cursor.sh/) is optional if you want a second IDE.
- [ ] Sign in to **Google AI Studio** (https://aistudio.google.com/) once and accept the terms.
- [ ] Bring one tiny app idea (UPI splitter, hostel mess menu, attendance tracker) — we'll build it live.

## 📚 References

- [Gamma documentation](https://help.gamma.app/) — official tips on prompting for decks.
- [Canva Magic Design](https://www.canva.com/magic-design/) — overview of the AI design assistant.
- [Garr Reynolds — Presentation Zen blog](https://www.presentationzen.com/) — the design-first philosophy worth absorbing.
- [Guy Kawasaki — 10/20/30 rule](https://guykawasaki.com/the_102030_rule/) — the only slide-count rule that's stood the test of time.
